### ISSUE TITLE
The suggestion to use collection abstractions does not apply when the Type is used by XmlSerializer

### ISSUE THREAD

**Issue by kristjantoots** [meziantou/Meziantou.Analyzer#124]
There's analyzer for `MA0016` which states that collection abstractions should be preferred instead of implementations. 

This recommendation does not apply when property of type `IList` is serialized or deserialized by the `XmlSerializer`, because `XmlSerializer` does not play well with collection abstractions. It can't handle any abstraction which does not implement `IXmlSerializable`, which built in collection abstractions do not. 

In such scenario the analyzer should not recommend to use collection abstractions because using them would simply produce `System.InvalidOperationException` when used by `XmlSerializer`. 

One of the possible options to determine whether type is intended to be used for XML operations is the presence of  `XmlAttributes`, which reside in the `System.Xml.Serilization` namespace. 

Would it make sense to add such exception to the analyzer? I could work on the pull request if this is something that should be done.

**Comment by meziantou** [comment]
Hi,

Thanks for the suggestion :)

Yes it could be a good idea to add an exception for xml serialization. I'm not sure of all the cases you have to handle. Here're the attributes I think the analyzer should handle:

1. The property is decorated by `XmlIgnore` => Analyze the property
2. The class is decorated by an attribute such as `XmlType`, `XmlRoot` => No diagnostic for the properties
3. The property is decorated by an attribute such as `XmlAttribute`, `XmlElement`, `XmlArray`, `XmlAnyAttribute`, `XmlAnyElement`, `XmlArrayItem`, `XmlText` => No diagnostic for the property

**Comment by meziantou** [comment]
@kristjantoots Are you ok with my analysis? Are there other cases that the analyzer should handle?

Do you still want to work on it?

**Comment by kristjantoots** [comment]
@meziantou The analysis looks good but to be honest, I have not given much thought to it yet. I was planning to get to it this week and if the longer timeframe suits you, then I'll happily work on it.

**Comment by meziantou** [comment]
If you want to implement it, I'll let you do so :) Don't worry for the time frame. It doesn't need to be this week or next week. Work on it when you have time and you want to spend this time coding!

**Comment by meziantou** [comment]
Fixed by 8dfcef169196691e00c1d49fb1b864da366730e6
