### ISSUE TITLE
MA0001: Ignore generated code

### ISSUE THREAD

**Issue by bddckr** [meziantou/Meziantou.Analyzer#131]
MA0001/`UseStringComparison` does not ignore generated code. I believe it's an oversight that this does not call `context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);`, like lots of other analyzers in this project.
https://github.com/meziantou/Meziantou.Analyzer/blob/73d8b97a3688765f92f93e7314eba9beb2ea7a9c/src/Meziantou.Analyzer/Rules/UseStringComparisonAnalyzer.cs#L24-L29

Is this intended? Perhaps there are more analyzers that are missing the configuration to ignore generated code?

**Comment by meziantou** [comment]
This is the first analyzer I wrote, so I didn't know some functionalities at the beginning. This is why there are some differences between the rules.

I think we should disable rules for generated code only when there is a real use case. Indeed, the generated code should follow the same rules as the rest of the code base.

Which tool generates the code in your case? (Is it a tool that is widely used?)

Also, you can disable a rule for a specific file/folder using the `.editorconfig` file:

````
[generated_file.cs]
dotnet_diagnostic.MA0001.severity = none
````

**Comment by bddckr** [comment]
>I think we should disable rules for generated code only when there is a real use case.

This is pretty much the exact opposite of what all the other analyzers do (that I use at least), including ones from Microsoft and the community.

>Indeed, the generated code should follow the same rules as the rest of the code base.

In a perfect world I'd agree but I have no authority over the various generators out there. As it's generated code the only way for me and my team to get rid of the analyzer diagnostics is to fork the generator (and potentially maintain it due to upstream not being interested in a merge).

>Which tool generates the code in your case?

My team uses (and used) a mix of these:
* https://docs.microsoft.com/aspnet/core/grpc/basics?view=aspnetcore-3.1#c-tooling-support-for-proto-files
* https://dotnet.github.io/orleans/Documentation/grains/code_generation.html
* https://github.com/amis92/RecordGenerator
* https://github.com/Husqvik/GraphQlClientGenerator

It looks like the only issue we have is with the last one here as we have to add that to the project manually. The rest are put in the `obj` folder as intermediate build output, which (AFAIK) completely hides them from analyzers in the first place.

---
>Also, you can disable a rule for a specific file/folder using the .editorconfig file:

That is a good solution for me and my team, though I'm still in the "opt-in rather than opt-out" boat. Some questions I'm currently pondering a few things due to this:
* Is there a way to disable by default but still allow the user to opt-in rather than opt-out?
* Can my team opt-out multiple rules without having to specifically mention them all? Wildcards don't seem to work.
* Visual Studio 16.5 preview 2 does support specifying whether a file is part of generated code as part of the .editorconfig. I assume this would solve my above issue of needing wildcard support otherwise, though I wonder if this still won't work for analyzers that do _not_ opt-out of caring about generated code. https://github.com/dotnet/roslyn/issues/3705#issuecomment-570687450
* This might help for other analyzer projects, but feels like it's way too much overhead for your project to maintain a list of "types" to care for (as you offer general-purpose rules): https://github.com/dotnet/roslyn/issues/39758

---

Thanks for the pointer to the .editorconfig solution - I'll use that for now! And a big thanks for this project in the first place ❤️

**Comment by meziantou** [comment]
I figure out that I've already added `ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None)` to most of the analyzers. So, I've logically added it to MA0001 and 2 others.

> Is there a way to disable by default but still allow the user to opt-in rather than opt-out?

I'm not aware of a way for a user to change the value of `context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None)` using a configuration. Maybe it will be supported with the editorconfig file (`generated_code = false`)

> Can my team opt-out multiple rules without having to specifically mention them all? Wildcards don't seem to work.

I don't think this is possible. You should open an issue on the Roslyn repository to ask for something like `dotnet_diagnostic.MA*.severity = none`.

> Visual Studio 16.5 preview 2 does support specifying whether a file is part of generated code as part of the .editorconfig. I assume this would solve my above issue of needing wildcard support otherwise, though I wonder if this still won't work for analyzers that do not opt-out of caring about generated code. dotnet/roslyn#3705 (comment)

I didn't know about that. Thanks for pointing that comment :)

> This might help for other analyzer projects, but feels like it's way too much overhead for your project to maintain a list of "types" to care for (as you offer general-purpose rules): dotnet/roslyn#39758

Everything possible :)
