### ISSUE TITLE
Add fixer for MA0071

### ISSUE THREAD

**Issue by meziantou** [meziantou/Meziantou.Analyzer#135]

**Comment by meziantou** [comment]
fixed by 0da2db14e9d2af0c15e011a40762a3f7c49eea59

/cc @louis-z

**Comment by louis-z** [comment]
@meziantou, it would have been nice to get a heads-up. I too implemented a fixer...

I also refactored the tests. Maybe I can still submit a PR for that.

**Comment by meziantou** [comment]
I accept PR that (any of the following):
- Improve tests,
- Use editor instead of editing the tree directly (seems more modern and easier to read),
- Replace `MustWrapInBlock` with something more resilient.
