### ISSUE TITLE
Split MA0020 Use direct methods instead of extension methods

### ISSUE THREAD

**Issue by nj0yeh** [meziantou/Meziantou.Analyzer#154]
Can you please extract the function `UseIndexerInsteadOfElementAt` from the MA0020 rule (https://github.com/meziantou/Meziantou.Analyzer/blob/master/src/Meziantou.Analyzer/Rules/OptimizeLinqUsageAnalyzer.cs) to an own rule? We want to deactivate it to improve readability, but keep the other rules from MA0020.

**Comment by meziantou** [comment]
I think we can split MA0020 into 3 rules:
- Count(), LongCount() -> Length, LongLength, Count
- FirstOrDefault() -> Find()
- ElementAt() -> Indexer `[]`

I have other priorities at the moment, so I won't have time to do it now. Feel free to contribute to the project if you want it soon :)

**Comment by meziantou** [comment]
Fixed by 4be12616afdc2d856ca70d9ae637f4942e0e2958

The new rule is MA0098
