### ISSUE TITLE
MA0073 Avoid comparison with bool constant with dynamic objects

### ISSUE THREAD

**Issue by nj0yeh** [meziantou/Meziantou.Analyzer#155]
MA0073 Avoid comparison with bool constant should not be raised the object is a `dynamic` object. It might be a Nullable<bool> field.

`((dynamic)x).Something == true`

**Comment by meziantou** [comment]
Thanks for reporting this issue!

@louis-z will check that :)

**Comment by meziantou** [comment]
The next version, [available in a few minutes](https://dev.azure.com/meziantou/GitHub%20projects/_build/results?buildId=5072&view=results), should fix this issue.

Thanks @louis-z for the PR :)

**Comment by louis-z** [comment]
My pleasure! It was an oversight on my part in the first place, so I'm glad I got the chance to fix it. ;)
