### ISSUE TITLE
Error AD0001: Analyzer 'Meziantou.Analyzer.Rules.DoNotUseBlockingCallInAsyncContextAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.

### ISSUE THREAD

**Issue by DrBrask** [meziantou/Meziantou.Analyzer#165]

**Comment by meziantou** [comment]
Hi,

- Do you have the full call stack? (should be available in the Error window) 
- What is the content of your file?

**Comment by DrBrask** [comment]
I dont get a call stack for this, just this:
...
C:\GIT\ft\RemoteLoggerFactory.cs(87,29,87,64): error MA0009: Regular expressions should not be vulnerable to Denial of Service attacks
**CSC : error AD0001: Analyzer 'Meziantou.Analyzer.Rules.DoNotUseBlockingCallInAsyncContextAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
CSC : error AD0001: Analyzer 'Meziantou.Analyzer.Rules.DoNotUseBlockingCallInAsyncContextAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.**

Maybe we can assume it's in the same file as the MA0009 error before it.
The rule that throws exceptions seems to be MA0045.
The code in the source file does not have .Wait() or Result as suggested in MA0045.... Actually nothing in this particular project uses .Wait() or .Result.

**Comment by meziantou** [comment]
Could you share the code around the line 87 of the file `RemoteLoggerFactory.cs`? (the full method if possible, or the full file content)

It used to have the full call stack when you click on the expand arrow in the first column... I don't know if this is still available.

**Comment by DrBrask** [comment]
Here is the method.
I've made line 87 bold - its the regex use from the previous warning.

private Task<ResponseBase> ConfigureCommand(Command command)
{
	foreach (var remoteLogger in _loggers) remoteLogger.SetLogLevel(LogLevel.Off);

	foreach (var loggingParameters in command.RemoteLoggingParameters)
	{
		var regularExpressionPattern = "^" + Regex.Escape(loggingParameters.LoggerNameFilter).Replace(@"\*", ".*").Replace(@"\?", ".") + "$";

		**var regex = new Regex(regularExpressionPattern);**

		foreach (var remoteLogger in _loggers)
		{
			if (regex.IsMatch(remoteLogger.LoggerName))
			{
				remoteLogger.SetLogLevel(loggingParameters.LogLevel);
			}
		}
	}

	return Task.FromResult((ResponseBase)new ConfigureRemoteLoggingResponse { Id = command.Id });
}

The only async thing here is the last code line with the Task.FromResult.


When I expand the arrow it it just add one more line that says "Analyzer Failure"

**Comment by DrBrask** [comment]
Okay bold didnt work inside the code segment.
But line 87 is the one with ** in it.

**Comment by meziantou** [comment]
Thanks, I'll try to reproduce the error on my machine

**Comment by meziantou** [comment]
I cannot reproduce your issue on my machine :(
However, I've enabled the Nullable Reference Types in the project to avoid potential NRE. In this specific rule the compiler complained about one line when `System.Console` is not defined, which should not be very common.

Can you get the latest version and try it in your project? If the problem still occurs, can you try to create a small repro project?

**Comment by DrBrask** [comment]
I tried the new version but I still get the exception.
My class is in a big project that I cannot upload here.
I might be able to make a smaller repo project, I don't know yet.

(I have another solution where VS hangs during compliation after I added the analyzer...
(Of cause that could be also VS))

**Comment by meziantou** [comment]
Maybe you can try to debug the analyzer on your machine. There are multiple ways to do it. The easiest is to remove the NuGet package from your project and use the following steps:
1. Clone this project 
2. Start the VS extension project (Meziantou.Analyzer.Vsix.csproj) with the debugger attached
2. Configure VS to break on first chance exceptions of type `ArgumentNullException` ([doc](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019))
3. Open your solution in the VS debug instance and wait for the exception to be thrown

**Comment by DrBrask** [comment]
I tried that.
I didnt get the exception.
I also tried with the previous version of that file.

I tried to remove all exteisions, repair VS and install it and the Nuget package again.
Now it seems to work.

**Comment by meziantou** [comment]
This is not the best fix, but at least it works! I will close the issue for now. Feel free to reopen it if you encounter the problem again.

Thanks for the time you spent on debugging 😊
