### ISSUE TITLE
Strange warning: MA0042 Use 'DeserializeAsync' instead of 'DeserializeAsync'

### ISSUE THREAD

**Issue by nrandell** [meziantou/Meziantou.Analyzer#169]
I've got this installed as a nuget package and it reports an MA0042 telling me to use DeserializeAsync instead of DeserializeAsync!!

    var octopusResponse = await JsonSerializer.DeserializeAsync<OctopusResponse<T>>(responseStream, SerializerOptions, ct);

This is using System.Text.Json.JsonSerializer in .Net 5.0

I'm not sure why it's doing this as I can't see anything wrong.

**Comment by meziantou** [comment]
Thanks for reporting the issue!

#170 should fix the bug. The new version (508) should be available soon after [the pipeline completes](https://dev.azure.com/meziantou/GitHub%20projects/_build/results?buildId=5787&view=results)
