### ISSUE TITLE
MA0003 ConfigureAwait(false) on gRPC calls

### ISSUE THREAD

**Issue by vchirikov** [meziantou/Meziantou.Analyzer#175]
Hi.
The generated grpc code has its own task types like `AsyncUnaryCall` and other.  So `.ConfigureAwait(false)` on them generates 
MA0003 `Name the parameter to improve the readability of the code`. 
I think we can add another exception for them or make more general solution for methods with name `ConfigureAwait`.
What do you think?

**Comment by meziantou** [comment]
Thanks for you feedback!

Any `ConfigureAwait(bool)` should be excluded from the analysis whatever the containing type is (not only for Task). This is something I changed a few days ago. Can you try to update to the latest version of the analyzer?

FYI, here's the list of exclusion for this rule:  https://github.com/meziantou/Meziantou.Analyzer/blob/master/src/Meziantou.Analyzer/Rules/NamedParameterAnalyzer.cs#L78

**Comment by vchirikov** [comment]
@meziantou , yep, with 1.0.516 the issue is gone. 
Thank you for your analyzers!
p.s. was 1.0.444.
