### ISSUE TITLE
Async method should have the Async suffix

### ISSUE THREAD

**Issue by meziantou** [meziantou/Meziantou.Analyzer#185]
Return type `Task`, `Task<T>`, `ValueTask`, or `ValueTask<T>`

- https://github.com/dotnet/runtime/issues/26908
- https://twitter.com/Nick_Craver/status/1296527511585726465

**Comment by bddckr** [comment]
I love this analyzer package, but I'm wondering if it's slowly becoming a huge monolith of all the rules users can come up with. The .NET ecosystem of analyzers already has other analyzer packages available that take care of threading and async details in particular. For this one VSTHRD200 of Microsoft.VisualStudio.Threading.Analyzers [handles it](https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/index.md).

As a user of this package (and plenty of others) I am trying to keep up with this analyzer package's changes to turn off new rules most of the time, as I already have other analyzers that handle specific scenarios. (I hope that turning off helps with saving some build overhead, but not sure if that's really the case.)

Don't get me wrong - I love your project! Just wondering if this trend continues. If it does I would love release notes or a change log I think - just to allow anyone who uses more than this analyzer package to play less whack-a-mole with new diagnostics 😄
Right now I take time every few weeks to go through the commits and then update the package reference, trying to focus on changes to the docs folder, but even enhancements to existing rules (which won't need a docs file update) I'm interested in as they might result in new diagnostics in my codebases.

**Comment by meziantou** [comment]
To sum up:
- Commit message must include the rule ID and a description of the change
- Consider disabling by default analyzers if FxCop/VSThreading has an equivalent rule
- Consider removing analyzers only if there is an issue (bug, doesn't support new syntax) and there is an alternative provided by FxCop

If you find an equivalent rule in FxCop or VSThreading, please open an issue so we can check if the rule is actually equivalent and should be disabled by default.
I'm only considering these 2 analyzers as there are plan to merge VSThreading into FxCop, and FxCop is more and more popular as VS suggest to use it with the gold bar. Note that I don't use Roslynator in my projects and SA (>= 1.2.0 for latest language support) is still in beta.
