### ISSUE TITLE
SortedDictionary<T,T> Should Throw MA0001 or Equivalent Warning

### ISSUE THREAD

**Issue by aolszowka** [meziantou/Meziantou.Analyzer#196]
First thank you for this Analyzer Library.

**Is your feature request related to a problem? Please describe.**
See https://github.com/dotnet/runtime/issues/43802 for background to this issue.

**Describe the solution you'd like**
Much like `string.Equals(string,string)` throws https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0001.md there are other places in the framework that have a default `StringComparer` should probably throw this warning.

One specific place is `SortedDictionary<T,T>`.

Failure to do so will result in different behaviors across .NET Core Platforms.

**Describe alternatives you've considered**
While this library is great I will also consider filing a feature request for out of the box Roslyn Analyzers because this behavior is so unexpected that I feel it should be out of the box (nothing against this excellent project!).

**Additional context**
To experience the issue first hand clone the repository (https://github.com/aolszowka/DotNetCoreSortedDictionaryCrossPlatform) referenced in the above bug report and allow GitHub Actions to build across platforms.

**Comment by meziantou** [comment]
Good catch!

The types supported by the rule MA0002 was hard-coded. I've improved it to be more generic, so it will detect SortedList, and other types / methods.

You can see the change in PR #197.

> While this library is great I will also consider filing a feature request for out of the box Roslyn Analyzers because this behavior is so unexpected that I feel it should be out of the box (nothing against this excellent project!).

I do support that! FxCop should detect this case. I'm pretty sure it does, but feel free to validate the behavior and open an issue on Roslyn-Analyzer if needed.

**Comment by aolszowka** [comment]
Confirmed Fixed as of 1.0.577; Thank you so much for the quick turn around!

![image](https://user-images.githubusercontent.com/2592881/97119337-305a4700-16d5-11eb-8c06-2049bb0777a3.png)
