### ISSUE TITLE
Suggest prefer using `await using` instead of `using`

### ISSUE THREAD

**Issue by VahidN** [meziantou/Meziantou.Analyzer#211]
C# 8.0 supports `await using`. For instance the `XmlWriter` implements the `IAsyncDisposable` too:
```C#
namespace System.Xml
{
    public abstract class XmlWriter : IAsyncDisposable, IDisposable
    {
```
Now we can write
```C#
using var xmlWriter = XmlWriter.Create(response.Body, xws);
```
Which will use the `Dispose()` method
Or
```C#
await using var xmlWriter = XmlWriter.Create(response.Body, xws);
```
Which will use the `DisposeAsync()` method automatically.

It would be great if this analyzer suggests "prefer using `await using`" for the types which are implementing the `IAsyncDisposable`.

**Comment by meziantou** [comment]
It seems the `IAsyncDisposable` interface is not needed. `await using` is valid as soon as the type has a compatible `DisposeAsync` method.

Fixed by c8600b96bcf8774d271de2cc098f6338eae63704 (version 1.0.641)
