### ISSUE TITLE
MA0006: make it possible to choose between string.Equals("foo", "bar", StringComparison.Ordinal) and "foo".Equals("bar", StringComparison.Ordinal)

### ISSUE THREAD

**Issue by egil** [meziantou/Meziantou.Analyzer#215]
Hi @meziantou, thanks for your work on these analyzers!

Anyway, a request. Personally I like `"foo".Equals("bar", StringComparison.Ordinal)` much better than `string.Equals("foo", "bar", StringComparison.Ordinal)`, but I understand that it is a matter of style, as both do the same, as far as I know.

I wonder if you can make this this rule configurable so it is possible to toggle between the two variants?

**Comment by meziantou** [comment]
It's possible to add more fixes. However, the fix you suggest changes the original behavior when the first value is `null`.

````c#
string a = null;
string b = null;
_ = a == b; // no error
_ = string.Equals(a, b, StringComparison.Ordinal); // no error
_ = a.Equals(b, StringComparison.Ordinal); // NullReferenceException when a is null
````

So, I'm not sure this is a good idea to propose it as it would change the original behavior.

**Comment by egil** [comment]
Ahh, yes, you have a point there. I humbly withdraw my suggestion :)
