### ISSUE TITLE
The Visual Studio extension is an old version

### ISSUE THREAD

**Issue by MatthewL246** [meziantou/Meziantou.Analyzer#220]
Right now, the extension at https://marketplace.visualstudio.com/items?itemName=Meziantou.Meziantou-Analyzer is not up-to-date. I personally like VSIX analyzers because they are easily installed for all of my projects, but if you do not want to maintain the extension that is fine. However, it is confusing if the extension is a different version than the NuGet package and source repository. It would be great if you could either update or officially deprecate and remove the extension.

**Comment by meziantou** [comment]
The VSIX is deprecated. The recommended way to use the analyzer is using [the NuGet package](https://www.nuget.org/packages/Meziantou.Analyzer/). I've updated the description of the VSIX extension to reflect this recent change.

If you want to add the analyzer to all of your project you can use a `Directory.Build.props` file at the root of your solution.

**Comment by Vijay-Nirmal** [comment]
Makes sense but as I am not a software architect, I don't have the power to include this in our project :-(
