### ISSUE TITLE
There are no destructors in C#

### ISSUE THREAD

**Issue by quixoticaxis** [meziantou/Meziantou.Analyzer#230]
C# has finalizers with destructor syntax. Updating the wording for MA0055 and MA0086 would be great.

**Comment by meziantou** [comment]
The .NET documentation use "Finalizers" while the spec use "Destructors". Both use "destructor" in their page url.
If you want to can submit a Pull Request to change destructor to finalizer.

- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#destructors

**Comment by quixoticaxis** [comment]
@meziantou the language specification ([ECMA-334 5th Edition / December 2017](https://www.ecma-international.org/publications-and-standards/standards/ecma-334/)) actually uses the term "finalizer" and contains the following clause:
> 15.13 Finalizers
> [Note: In an earlier version of this standard, what is now referred to as a "finalizer" was called a 
> "destructor". Experience has shown that the term "destructor" caused confusion and often resulted to 
> incorrect expectations, especially to programmers knowing C++. In C++, a destructor is called in a 
> determinate manner, whereas, in C#, a finalizer is not. To get determinate behavior from C#, one should
> use Dispose. end note]

It seems that online documentation is out-of-sync. Not that it matters much, of course.
