### ISSUE TITLE
MA0028 StringBuilder optimizes to wrong AppendFormat format

### ISSUE THREAD

**Issue by jafaber** [meziantou/Meziantou.Analyzer#244]
**Context**
Rule identifier: _MA0028_
Target Framework: _.NET 5.0_
Language version: _9.0_

**Describe the bug**
`builder.Append(b.ToString("X2", CultureInfo.InvariantCulture));`

is optimized to:

`builder.AppendFormat(CultureInfo.InvariantCulture, "X2", b);`

which is the wrong format string. It should be 

`builder.AppendFormat(CultureInfo.InvariantCulture, "{0:X2}", b);` as is also described in the documentation at https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0028.md (last example).

https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0A4gDYD2ARgIbECWAXpcDaVANzpa4EAqApgB7B2adOQCewXtnLYAvNgAU4yQEoA5AC01wgMrAwNKAHMAQhBrEAJrzDTzVm3OxReAdwUrho+9bD4AggAOgbxQlkr43KR6BsYKAEQAGgjxADTYAMIQxMAQYLwAklAAZqT4RQBulAaUUMBZOXm8KioBwaGWADKGvB7C5D42bSFhAGKkYAC2jAoNuflFpeVQVTV1c03pSSnp5K1BI109fd4WvsMd41MzGwslZZXVNLX12fO8WwDemCDJAL5paT7dphbouE4iDBIACcSkGYE8QA

**Comment by jafaber** [comment]
If I'm not mistaken, this would be the unit test that matches the documentation example:

```c#
        [Fact]
        public async Task Append_AppendFormat()
        {
            await CreateProjectBuilder()
                  .WithSourceCode(@"using System.Text;
class Test
{
    void A()
    {
        [||]new StringBuilder().Append(1.ToString(""n1"", null));
    }
}")
                  .ShouldFixCodeWith(@"using System.Text;
class Test
{
    void A()
    {
        new StringBuilder().AppendFormat(null, ""{0:n1}"", 1);
    }
}")
                  .ValidateAsync();
        }
```

**Comment by meziantou** [comment]
Thanks for reporting the issue. The next version should be available in [a few minutes](https://github.com/meziantou/Meziantou.Analyzer/actions/runs/936405559) :)

**Comment by jafaber** [comment]
Wow, very fast! I just tested it and it's working perfectly for my use case. Cheers!
