### ISSUE TITLE
New rule request: MA0042 for all methods (not just async)

### ISSUE THREAD

**Issue by Chiel92** [meziantou/Meziantou.Analyzer#247]
**Is your feature request related to a problem? Please describe.**
[Calling `.Wait()` or `.Result` on a task can result in a deadlock](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html), regardless of whether it's done in an async method or not. It all depends on the context, but it's a good default practice to either be async all the way, or not at all. In other words, don't block on tasks by default.

There are exceptions. If a programmers knows what he is doing and uses ConfigurateAwait(false) everywhere, or if some code base is guaranteed to run without a synchronization context that forces the same thread, it's fine to call `Result` or `Wait()`. But is is by no means a given, and a programmer should have explicitly thought about this.

**Describe the solution you'd like**
I would like MA0042 to apply to all methods by default, and have a setting to restrict it to async methods. This forces the programmer to either go with the safe default, or explicitly commit to a different (but potentially dangerous) approach by tweaking the rule settings.

**Describe alternatives you've considered**
- The same as above but have the default be like it is now: only for async methods, and have a setting to make it apply to all methods. Less safe, but "backward compatible".
- Have a completely separate rule, either turned on or off by default.

**Additional context**
MA0004 tries to detect the synchronization context by default. However, this is not always possible to detect. Some library code may have nothing to do with WinForms, but still a WinForms app may use that library and inject callbacks (like logger functions, to name a common one) which update form controls etc. If that library used `ConfigureAwait(false)` everywhere, this will give problems. So I let us please refrain from doing something similar for this rule, as it may give a false sense of security.

**Comment by meziantou** [comment]
MA0042 only reports when the fix doesn't require to change the method signature. What you want is MA0045, which is not enabled by default. You need to manually enable this rule using an `.editorconfig` file

````
# Missing cancellationtoken (even if it requires method signature change)
dotnet_diagnostic.MA0032.severity = suggestion

# Avoid blocking call (even if it requires method signature change)
dotnet_diagnostic.MA0045.severity = suggestion

# Use await using (even if it requires method signature change)
dotnet_diagnostic.MA0080.severity = suggestion
````

You can configure [MA0004](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0004.md) to not be _smart_ and always report

````
[.*cs]
 # (default) Try to detect the current context and report only if it considers ConfigureAwait is needed
MA0004.report = DetectContext

# Always report missing ConfigureAwait whatever the context
MA0004.report = Always
````

**Comment by Chiel92** [comment]
Thanks, `MA0045` had not caught my eye.
