### ISSUE TITLE
Question: Should I use other analyzers with this?

### ISSUE THREAD

**Issue by kotx** [meziantou/Meziantou.Analyzer#251]
I know that there's some overlap with `Microsoft.CodeAnalysis.NetAnalyzers`, so is it recommended to only use `Meziantou.Analyzer` or to use it along with analyzers such as `StyleCop.Analyzers` or `Microsoft.CodeAnalysis.NetAnalyzers`?

**Comment by meziantou** [comment]
You should use `Microsoft.CodeAnalysis.NetAnalyzers`, then add other analyzers (as many as you want). You can disable overlapping rules using the editorconfig file. FYI, I try to keep a list of overlapping rules: https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md

**Comment by kotx** [comment]
Thanks a lot.
