### ISSUE TITLE
New rule: Don't write to your own parameters

### ISSUE THREAD

**Issue by VahidN** [meziantou/Meziantou.Analyzer#255]
This rule [is explained here](https://github.com/dotnet/aspnetcore/issues/24599#issuecomment-697588562) for the Blazor apps and a lot of newcomers don't know it and can be mistakenly forgotten easily.

**Comment by meziantou** [comment]
ASP.NET Core already provides analyzers to ensure best practices. I think you should first create an issue on [the ASP.NET Core repository](https://github.com/dotnet/aspnetcore/issues/new/choose) to suggest this new analyzer. Depending on their response, we can see what to do here.
