### ISSUE TITLE
AvoidClosureWhenUsingConcurrentDictionaryAnalyzer has wrong namespace in version 1.0.678

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [meziantou/Meziantou.Analyzer#273]
**Context**
Rule identifier: _MA0000_
Target Framework: _.NET 5.0_
Language version: _9.0_

AvoidClosureWhenUsingConcurrentDictionaryAnalyzer  is in Meziantou.Analyzer.Rules.Meziantou.Analyzer.Rules instead of Meziantou.Analyzer.Rules

**Comment by meziantou** [comment]
Thanks! Fixed in https://github.com/meziantou/Meziantou.Analyzer/commit/07c76c969eed39934451193f7843ee636663f150
