### ISSUE TITLE
warning about (not *from*) AvoidClosureWhenUsingConcurrentDictionaryAnalyzer

### ISSUE THREAD

**Issue by rwv37** [meziantou/Meziantou.Analyzer#275]
**Context**
Rule identifier: _CS8032_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
Upon updating projects from version 1.0.673 to version 1.0.681, I've started getting the following warning whenever I build:

CS8032
An instance of analyzer Meziantou.Analyzer.Rules.AvoidClosureWhenUsingConcurrentDictionaryAnalyzer cannot be created from C:\Users\bob\.nuget\packages\meziantou.analyzer\1.0.681\analyzers\dotnet\cs\Meziantou.Analyzer.dll: Could not load type 'Meziantou.Analyzer.Rules.AvoidClosureWhenUsingConcurrentDictionaryAnalyzer' from assembly 'Meziantou.Analyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'..	Rwv37.IO		1	Active	System.TypeLoadException: Could not load type 'Meziantou.Analyzer.Rules.AvoidClosureWhenUsingConcurrentDictionaryAnalyzer' from assembly 'Meziantou.Analyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions`1.GetAnalyzersForTypeNames(Assembly analyzerAssembly, IEnumerable`1 analyzerTypeNames, Boolean& reportedError)

**To Reproduce**
Sorry that I can't be specific, but as far as I know, it's just "build a project that uses version 1.0.681".

**Comment by meziantou** [comment]
Do you have any error when building the project from the command line (`dotnet build`)? Do you still have the error after restarting the IDE? Which IDE do you use?

**Comment by rwv37** [comment]
I use VS2022 Community, and generally speaking I do builds from within it. I am pretty confident that as of yesterday, restarting the IDE had no effect on this. However:

Upon your suggestion, I tried out `dotnet build` a minute ago. It did _not_ occur. Furthermore, I then opened the project in the IDE to double check on your "restarting the IDE" question, and now (without even restarting the IDE) I did _not_ get the error when building from within the IDE.

One thing that stands out to me is that this one CLI build of this one project seems to have cleared up the problem not only for this one project, but also for other projects that I had previously built in the IDE, and even for projects that I upgraded to 1.0.681 only just a moment ago (i.e. I had not updated them prior to this one `dotnet build` for that one other project).

So, I'm now guessing that maybe this resolution might have something to do with this that came out in the CLI build output:

> Restored C:\Users\bob\Bob\trunk\Dev\DotNet\Rwv37\IO\Rwv37.IO.Tests\Rwv37.IO.Tests.csproj (in 253 ms).

I don't know the building process well enough to really understand what this means, but I know it has something to do with NuGet packages... maybe there was some copy of 1.0.673 cached somewhere, interfering somehow with 1.0.681, and the CLI build cleaned things up?

**Comment by meziantou** [comment]
From my experience, updating a Roslyn analyzer from VS sometimes needs a restart of VS to ensure it loads the updated version of the analyzer into the Roslyn process.

I don't think there is something I can do on my side to avoid this error. You can report the error to the VS team as it seems to be an error with VS:

![image](https://user-images.githubusercontent.com/509220/147427117-92273bb6-cd31-4844-822c-4be5d4be3412.png)

**Comment by rwv37** [comment]
OK, thank you!
