### ISSUE TITLE
Docs: MA0016 similar to CA2227

### ISSUE THREAD

**Issue by Piedone** [meziantou/Meziantou.Analyzer#277]
**Is your feature request related to a problem? Please describe.**
Noticed that [MA0016](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0016.md) showed a violation where we previously suppressed [CA2227](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227).

**Describe the solution you'd like**
I'd add a note to the docs about the similarity of the two analyzers. CA2227 is about read-only collections though, not abstractions.

**Describe alternatives you've considered**
Hiding this info from the project's users :).

**Additional context**
-

**Comment by meziantou** [comment]
I don't see how these two rules are related:
- CA2227: Collection properties should be read only => remove setter
- MA0016: Use abstraction instead of concrete collection => e.g. change type from `List<T>` to `IList<T>`

It is also not clear what you want to document here?

**Comment by Piedone** [comment]
Ah yeah, you're right, misunderstood.
