### ISSUE TITLE
Docs: MA0069 is the same as CA2211

### ISSUE THREAD

**Issue by Piedone** [meziantou/Meziantou.Analyzer#287]
**Is your feature request related to a problem? Please describe.**
[MA0069](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0069.md) seems to be the same as [CA2211](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211). Actually, the description is the same too.

**Describe the solution you'd like**
Add a not about this to [the docs](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md).

**Describe alternatives you've considered**
Keeping this info to myself :).

**Additional context**
N/A

**Comment by meziantou** [comment]
Thanks! I've updated the documentation

**Comment by Piedone** [comment]
Thank you!
