### ISSUE TITLE
NewRule: Remove parameter if you use CallerArgumentExpressionAttribute.

### ISSUE THREAD

**Issue by SebastianStehle** [meziantou/Meziantou.Analyzer#292]
Hi, I really like your analyzers. I have a feature request.

**Is your feature request related to a problem? Please describe.**

Lets say you have a guard class.

```
class Guard {
    public static void NotNull(object? target, [CallerArgumentExpression] string? parameterName = null)
    {
        if (target == null)
        {
            throw new ArgumentNullException(parameterName);
        }
    }
}
```

If the class is used like this:

```
Guard.NotNull(foo, nameof(foo));
```

You can omit the second argument and just call:

```
Guard.NotNull(foo);
```

**Describe the solution you'd like**
It would be great to have a rule for that with a refactoring.

**Additional context**
Only works with .NET 6+

More about this: https://andrewlock.net/exploring-dotnet-6-part-11-callerargumentexpression-and-throw-helpers/#introducing-callerargumentexpression-

**Comment by meziantou** [comment]
New rule available: MA0108 - Remove redundant argument value

**Comment by SebastianStehle** [comment]
Awesome

**Comment by SebastianStehle** [comment]
AFAIK the attribute is available since .net 5 but it i
only works with .net6. I don't see a check of the runtime or compiler version

**Comment by meziantou** [comment]
I've added a check for the language version in #295

**Comment by SebastianStehle** [comment]
Thx, it works great btw :)
