### ISSUE TITLE
MA0048 Imrovements: Ignore razor pages.

### ISSUE THREAD

**Issue by SebastianStehle** [meziantou/Meziantou.Analyzer#299]
MA0048 always triggers for razor pages.

A razor page has two files.

<Name>.cshtml
<Name>.cshtml.cs

But the model class is called <Name>Model

Would be great to have an special case for this in the rule.

**Comment by meziantou** [comment]
It seems a specific need, so I don't think the rule should be changed (except if you can prove me I'm wrong 🙂).
That's being said, you can disable the rule for these files using an `.editorconfig` file:

````
[*.cshtml.cs]
dotnet_diagnostic.MA0048.severity = none
````

**Comment by SebastianStehle** [comment]
I know that I can disable it. It is more a minor improvement to make the life easier if you razor pages. The file structure above is the default for razor pages.

**Comment by meziantou** [comment]
> The file structure above is the default for razor pages.

Could you share a few examples of public projects (GitHub would be fine) that use this structure? Is it VS that creates this structure, or maybe `dotnet new`?

I would like to understand the problem and be sure it is not a project specific issue. This helps provide the right fix.
