### ISSUE TITLE
MA0004 fix produces CS0029 compilation error in using construct

### ISSUE THREAD

**Issue by ohmineer** [meziantou/Meziantou.Analyzer#308]
**Context**
Rule identifier: _MA0004_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
MA0004 automatic fix produces CS0029 compilation error in using construct for IAsyncDisposables.

**To Reproduce**
````c#
// Original code
await using (FileStream fStream = jsonFile.OpenRead())
{
    // More code here
}

// Proposed fix
await using (FileStream fStream = jsonFile.OpenRead().ConfigureAwait(false))
{
    // More code here
}
````

Original code produces `MA0004 - Use Task.ConfigureAwait(false) as the current SynchronizationContext is not needed`.
Proposed solution leads Roslyn to throw `CS0029 - Cannot implicitly convert type 'System.Runtime.CompilerServices.ConfiguredAsyncDisposable' to 'System.IO.FileStream' `

**Additional context**
It looks like one can make the compiler and the analyzer happy by declaring and additional variable:
````c#
FileStream fStream = jsonFile.OpenRead();
await using (fStream.ConfigureAwait(false))
{
    // More code here
}
````
More details here: [https://www.tabsoverspaces.com/233779-using-await-using-iasyncdisposable-with-configureawait](https://www.tabsoverspaces.com/233779-using-await-using-iasyncdisposable-with-configureawait)

Thanks in advance for your support!

**Comment by meziantou** [comment]
I think we can change the fixer for `await using`. Note that the new fix would change the scope of the variable. So, the fixed code may still generate an invalid code in cases such as the following:

````c#
// Valid
await using (var a = new Disposable());
await using (var a = new Disposable());

// Not valid
var a = new Disposable();
await using (a.ConfigureAwait(false));
var a = new Disposable(); // error
await using (a.ConfigureAwait(false));
````

Also, I don't think that supporting `using` with multiple variables is required as this is not frequent. This would make the fixer more complicated for very little usages.

**Comment by ohmineer** [comment]
Hi @meziantou,

Thanks for the quick solution. I am still observing the warning in the following case:
![MA0004](https://user-images.githubusercontent.com/8396492/156756773-acde9a51-8829-41be-a9db-754b6ffa8ac6.png)

I am not sure whether is an edge case I should ignore or something it can be fixed. Applying the fix does not seem a solution:
````C#
AsyncServiceScope scope = host.Services.CreateAsyncScope(); // This line still shows the warning MA0004
await using (scope.ConfigureAwait(false)
{
}
````

**Comment by meziantou** [comment]
I can't reproduce the issue with the latest version of the analyzer (1.0.696)

````xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Analyzer" Version="1.0.696" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>

</Project>
````

````c#
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
class ClassTest
{
    async Task Test()
    {
        ServiceProvider services = null!;
        AsyncServiceScope scope = services.CreateAsyncScope();
        await using (scope.ConfigureAwait(false))
        {
        }
    }
}
````

Do you have the warning when you build using the command line (`dotnet build`)? (sometimes Visual Studio is not able to correctly load analyzers after updating the version...)

**Comment by ohmineer** [comment]
You are correct, it looks like my project did not restore correctly so I was still using the previous version. Sorry for the confusion.
