### ISSUE TITLE
MA0111 / rules that dot not apply to all TFM

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#357]
I just noticed that you introduce MA0111 (which is great, by the way). The only thing is that this rule only applies to .NET 6.0+ as `Create(IFormatProvider, DefaultInterpolatedStringHandler)` was only introduced in .NET 6.0.

How do generally deal with this? Do you:

1. Expect people to disable this rule (`dotnet_diagnostic.MA0111.severity = none`)

1. Intend to implement rules in such a way that they only report a diagnostic if they apply to the current TFM

Personally, I would prefer the latter. But I'm sure the former is easier to implement.

**Comment by meziantou** [comment]
The rule detects the method `string.Create(IFormatProvider, DefaultInterpolatedStringHandler)` exists. Roslyn doesn't have the notion of TFM. So, you need to check for language version and available methods.

https://github.com/meziantou/Meziantou.Analyzer/blob/main/src/Meziantou.Analyzer/Rules/UseStringCreateInsteadOfFormattableStringAnalyzer.cs#L34-L40

**Comment by drieseng** [comment]
Great, even better.
