### ISSUE TITLE
MA0111: Performance

### ISSUE THREAD

**Issue by MZole** [meziantou/Meziantou.Analyzer#359]
Could you please elaborate on the exact benefit of [MA0111](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0111.md)? I saw that this is under the performance category, but I couldn't figure out why string.Create is better than FormattableString.

**Comment by meziantou** [comment]
`FormattableString.Invariant($"")` is slower than `string.Create(CultureInfo.Invariant, $"")`. You can run the following Benchmark using `BenchmarkDotNet`

````c#
using System.Globalization;
using BenchmarkDotNet.Attributes;

namespace Benchmark;

[ReturnValueValidator]
public class StringCreateBenchmark
{
    int a = 1;
    DateTime b = DateTime.UtcNow;

    [Benchmark]
    public string StringCreate()
    {
        return string.Create(CultureInfo.InvariantCulture, $"text {a} test {b}");
    }

    [Benchmark]
    public string FormattableStringInvariant()
    {
        return FormattableString.Invariant($"text {a} test {b}");
    }
}
````

````
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22622
AMD Ryzen 7 5800X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.100-preview.7.22377.5
  [Host]     : .NET 7.0.0 (7.0.22.37506), X64 RyuJIT
  DefaultJob : .NET 7.0.0 (7.0.22.37506), X64 RyuJIT
````

|                     Method |     Mean |   Error |  StdDev |
|--------------------------- |---------:|--------:|--------:|
|               StringCreate | 157.2 ns | 3.19 ns | 6.00 ns |
| FormattableStringInvariant | 170.4 ns | 3.26 ns | 6.20 ns |

**Comment by MZole** [comment]
Thank you for your answer!

**Comment by Piedone** [comment]
Could you please also add this explanation to the rule file?

**Comment by meziantou** [comment]
I've updated the documentation

**Comment by Piedone** [comment]
Thank you!
