### ISSUE TITLE
Do not report MA0053 for a public class containing benchmark methods

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#368]
**Is your feature request related to a problem? Please describe.**
BenchmarkDotNet requires a class containing benchmarks to be public, non-sealed and non-static.
Even though you can argue that it's not or less common to run an analyzer on benchmark projects, I run them on all projects.
Currently, I have to disable **MA0053** for benchmark projects (or disable it for each type containing benchmark methods).

**Describe the solution you'd like**
Ideally, **MA0053** would not be reported for a type that is public, non-static and which contains at least one public instance method that has been decorated with a **BenchmarkDotNet.Attributes.Benchmark** custom attribute.

I can definitely surely understand it if you do not accept such a request as I'm sure it's fairly uncommon to enable **MA0053** for benchmark projects.

**Describe alternatives you've considered**
Disable **MA0053** for benchmark projects, or disable **MA0053** for each type containing benchmark methods.

**Comment by meziantou** [comment]
Thanks for suggesting this improvement!

It should be fixed by 2e7cf84c4d0002f1100f0ca8eeed32a9a8e887ee and included in version 1.0.721

**Comment by drieseng** [comment]
@meziantou, damn you're fast. Thx!
