### ISSUE TITLE
Introduce rule to encourage static lambdas and anonymous methods

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#369]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, there's no rule (neither in **Meziantou.Analyzer**, nor the **.NET Compiler Platform analyzers**) that reports a diagnostic when a lambda or anonymous method could be made static.

**Describe the solution you'd like**
A diagnostic is reported when an anonymous method or lambda does not capture any local or instance state from containing scopes, but does not have a 'static' modifier.

**Describe alternatives you've considered**
There are no alternatives.

**Comment by meziantou** [comment]
The `static` keyword for lambda is a way to tell the compiler it should report an error when the lambda captures locals. There is no change in the generated code if the lambda doesn't captures locals and hasn't the `static` keyword.

To my mind, it seems like you need performance in specific methods, and one way to do it is to prevent allocations. In this case you could add the `static` keyword to ensure the lambda to explicitly express this need. But, I don't see the value to add `static` keyword everywhere as it adds more code where it is not needed and doesn't bring performance benefits.

That's being said, if someone wants to contribute and implement this rule, it should be disabled by default as it would be noisy and doesn't add value in most cases. Also, it should reuse the `DetectClosure` method in the `AvoidClosureWhenUsingConcurrentDictionaryAnalyzer` (move it to a helper class).

**Comment by drieseng** [comment]
I see the static modifier as a way to force people to reflect when they - intentionally or unintentionally - introduce captures for a lambda that originally did not have any.

It's indeed mostly important for performance critical code.

I'll put this on my to-do list, and close this issue.
