### ISSUE TITLE
Special case Int128/UInt128 for MA0075 and MA0076

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#370]
Neither MA0075 nor MA0076 should not be reported when the type of the operand is **System.UInt128**.
In case of **System.Int128**, these diagnostics should not be reported if the operand is a positive constant.
I'll take a stab at this later.

**Comment by meziantou** [comment]
The latest version excludes `UInt128` (and `UIntPtr`).

> In case of System.Int128, these diagnostics should not be reported if the operand is a positive constant.

This part is not done. This is more complex than native types as there is no constant. You have to infer the value from the ctor arguments, or the property used to create the value (e.g. `Int128.One`). You can submit a PR if you want.
