### ISSUE TITLE
MA0042 reports usage of EF Core Add method to use AddAsync

### ISSUE THREAD

**Issue by MxNbrt** [meziantou/Meziantou.Analyzer#374]
**Context**
Rule identifier: MA0042
Target Framework: .NET 6.0
Language version: 10.0

**Describe the bug**
Using the EF DbContext method Add https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.add?view=efcore-6.0 results in the following info:

> Use 'AddAsync' instead of 'Add

This is only partly correct, as AddAsync should only be used in some rare cases, even Microsoft writes that on their article https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-6.0 stating that 

> This method is async only to allow special value generators, such as the one used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used.

As the AddAsync method uses another roundtrip to the database, it is recommended in most scenarios to use Add.

PS: The same goes for AddRange vs AddRangeAsync

**To Reproduce**

1. Create a new .NET 6 project
2. Add EF Core
3. Add a DbContext and DbSet
4. Call the Add method on DbContext or DbSet

**Proposed solution**
Exclude the Add and AddRange method from MA0042

**Comment by meziantou** [comment]
Thanks for the suggestion! It should be fixed by https://github.com/meziantou/Meziantou.Analyzer/commit/c219d52648d21cfab854adee4ff9bd6f7e1436fd and will be available in the next version 1.0.724.

**Comment by MxNbrt** [comment]
@meziantou Wow that was quick. Thank you very much.
