### ISSUE TITLE
MA0042 reports usage of EF Core DbSet<TEntity> Add method to use AddAsync

### ISSUE THREAD

**Issue by MxNbrt** [meziantou/Meziantou.Analyzer#376]
**Context**
Rule identifier: MA0042 
Target Framework: .NET 6.0
Language version: 10.0

**Describe the bug**
See also #374 but as I integrated the new version of Meziantou Analyzer, I noticed that there are two Add[Async] and AddRange[Async] methods. One is on DbContext (which was fixed by #374 ) and one is on DbSet<TEntity> https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addasync?view=efcore-6.0

In this issue, the DbSet<TEntity> should be fixed.

**To Reproduce**

* Create a new .NET 6 project
* Add EF Core
* Add a DbContext 
* Add a DbSet
* Call the Add method on DbSet

**Proposed solution**
Exclude the Add and AddRange method of DbSet<TEntity> from MA0042

**Comment by meziantou** [comment]
I've fixed the detection of `DbSet<T>`, so it should now correctly detect it. So, it will not report a diagnostic. 

Fixed by eb7d1cf0f35d012c42bce710a02694710d6e947d

**Comment by MxNbrt** [comment]
It works now as expected, that you very much for the fast fix.
