### ISSUE TITLE
Concurrency problem in `DoNotUseBlockingCallInAsyncContextAnalyzer`

### ISSUE THREAD

**Issue by Greg-Smulko** [meziantou/Meziantou.Analyzer#389]
**Context**
Target Framework: _.NET 6.0_
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET

Seems to be introduced in v1.0.729 and still present in v1.0.730.

**Describe the bug**
When executing the build, the following error was raised:
> CSC : error AD0001: Analyzer 'Meziantou.Analyzer.Rules.DoNotUseBlockingCallInAsyncContextAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'.

**To Reproduce**
Well, as with the concurrency bugs, it's not really overly deterministic.

**Comment by meziantou** [comment]
It was easy to spot! Should be fixed in the next version (available in a few minutes on NuGet)
