### ISSUE TITLE
Interest in a ReturnTaskDirectlyAnalyzer?

### ISSUE THREAD

**Issue by CollinAlpert** [meziantou/Meziantou.Analyzer#391]
Hi, I made an analyzer which detects instances of a `Task` which can be returned directly: https://github.com/CollinAlpert/ReturnTaskDirectlyAnalyzer

I'd love more people to use it and was wondering if you'd be interested in me opening a PR adding it to this package.

**Comment by meziantou** [comment]
Hi, you can submit a PR with the rule to remove await when this is not needed.
- You can add a new id in `RuleIdentifiers.cs`
- Don't forget to generate the documentation file using the `DocumentationGenerator` project

Removing `await` changes the behavior of methods ([exception handling, debugging, and surely other things](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/19a49baea31a64d8386be1c3b1428d0775520d32/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task)), but it improves the performance. I think it is ok to set the analyzer level to Info.

**Comment by CollinAlpert** [comment]
That's interesting. I know this pattern changes behavior, however I never had the problem of an unreadable stack trace due to this. There were always plenty of other async methods which did show up.

**Comment by CollinAlpert** [comment]
That's interesting. I know this pattern changes behavior, however I never had the problem of an unreadable attack trace due to this. There were always plenty of other async methods which did show up.
