### ISSUE TITLE
Compliant resolution for MA0076 conflicts with MA0111

### ISSUE THREAD

**Issue by royberris** [meziantou/Meziantou.Analyzer#394]
**Context**
Rule identifier: _MA0076_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
MA0076 will tell you to use `FormattableString.Invariant` but this interfears with MA0111 which tells you to use `string.Create` instead of `FormattableString.Invariant`.
 
It would be logic to straight go to the resolution of MA0111 instead of first resolving MA0076 to be instantly prompted with a message to fix MA0111.

**Comment by meziantou** [comment]
Good suggestion! Note that both fixes should be available because some projects target multiple frameworks, and the `string.Create` method may not be available for all targets. So, users must have the choice.
