### ISSUE TITLE
MA0004 suggesting adding ConfiguredAsyncDisposable to AsyncServiceScope

### ISSUE THREAD

**Issue by royberris** [meziantou/Meziantou.Analyzer#403]
**Context**
Rule identifier: _MA0004_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
When creating an `AsyncServiceScope` with `IScopeProvider.CreateAsyncScope` the MA0004 rule will suggest to add `ConfigureAwait` to it. This then returns an `ConfiguredAsyncDisposable` which is not compatible with `AsyncServiceScope`. 

**To Reproduce**

Create a new async scope with the `IScopeProvider`. in an `await using` block. MA0004 will suggest adding `ConfigureAwait`. This will break the code because we cannot go from `ConfiguredAsyncDisposable` to `AsyncServiceScope`.

````c#
await using (var scope = serviceProvider.CreateAsyncScope().ConfigureAwait(true))
{
  scope.ServiceProvider.GetService<Foo>(); // will not work because ConfiguredAsyncDisposable has no property named ServiceProvider.
}
````

**Comment by meziantou** [comment]
The analyzer works as intended. It detects the missing `ConfigureAwait` and suggest the following fix:

````
var scope = serviceProvider.CreateAsyncScope();
await using (scope.ConfigureAwait(false))
{
}
````
