### ISSUE TITLE
New rule: Don't start Blazor URL's with "/"

### ISSUE THREAD

**Issue by VahidN** [meziantou/Meziantou.Analyzer#409]
We usually don't care about the defined URL's in our Blazor apps and it always works until we are going to publish it in a subdomain. In this case, all of the URL's starting with "/" will refer to the main domain and not the current subdomain and the app won't run correctly. So it's a best practice to do not start Blazor's URL's with "/" everywhere, including:
- API URL's
- NavLink URL's
- NavigationManager.NavigateTo()

**Comment by meziantou** [comment]
This rule would produce some false-positive. Indeed, there are valid use-cases for "/url".
In another context, I would think this is ok to have a few false-positive as you can remove warnings using attributes or directives. 

In a razor file, this is much harder to disable a warning. The current state of Visual Studio + Razor editor is not that great... So, it would be hard for users to disable a warning when a false-positive is reported. Maybe this can be reevaluated when the tooling is better.
