### ISSUE TITLE
File Version doesnt match nuget package version

### ISSUE THREAD

**Issue by gizmohd** [meziantou/Meziantou.Analyzer#413]
![image](https://user-images.githubusercontent.com/1664013/199766914-a8e8d253-2fb3-4e8b-94c3-9a82e548aec5.png)

Getting an error in visual studio because the file/dll version doesnt match the nuget version..

![image](https://user-images.githubusercontent.com/1664013/199767882-4c305648-e780-4fcd-8908-069da832f152.png)

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Meziantou.Analyzer.Rules.DoNotOverwriteRazorComponentParameterValue cannot be created from C:\Users\<user>l\.nuget\packages\meziantou.analyzer\**1.0.744**\analyzers\dotnet\cs\Meziantou.Analyzer.dll: Could not load type 'Meziantou.Analyzer.Rules.DoNotOverwriteRazorComponentParameterValue' from assembly 'Meziantou.Analyzer, Version=**1.0.0.0**, Culture=neutral, PublicKeyToken=null'..	Landstar.Cloud.Clients.Core (net6.0)	C:\Users\<user>\.nuget\packages\meziantou.analyzer\1.0.744\analyzers\dotnet\cs\Meziantou.Analyzer.dll	1	Active

**Comment by meziantou** [comment]
This error can happen when you use an older version of Roslyn / Visual Studio or sometimes when you update an Analyzer package.

- Does the project build with `dotnet build`? Are there warnings about analyzers?
- What's the output of `dotnet --info`?
- What's the full version of Visual Studio? (Available in Help / About Microsoft Visual Studio)
- Is there an update of Visual Studio available?
- What is the version of Roslyn? You can add `#error` version in a cs file of your project. This should report the version of Roslyn in the error window or in the build output. See [Getting Roslyn (C# compiler) and Language versions](https://www.meziantou.net/getting-roslyn-csharp-compiler-and-language-versions.htm) for more information
