### ISSUE TITLE
MA0004 applies only in rare places in modern .NET 

### ISSUE THREAD

**Issue by ShaharPrishMSFT** [meziantou/Meziantou.Analyzer#417]
**Context**
Rule identifier: _MA0004_
Target Framework: _.NET 6.0_
Language version: _10.0_

**Describe the bug**
This is too wide a net that makes code less readable. It does not, for example, apply to ASP.NET Core (5 for sure, I think it doesn't apply to 3 either)

**To Reproduce**
Code or steps to reproduce the behavior:

````c#
Code to reproduce the issue
````

**Additional context**

**Comment by meziantou** [comment]
.NET has many `SynchronizationContext` (Blazor, WinForms, WPF, WebForms, xUnit, etc.), so it could be useful to use `ConfigureAwait(false)` for performance reasons.

If the rule doesn't apply to your context, it's fine to disable the rule using the `.editorconfig`

````
dotnet_diagnostic.MA0004.severity = none
````
