### ISSUE TITLE
Cannot load analyzer when targeting .NET 7.0

### ISSUE THREAD

**Issue by royberris** [meziantou/Meziantou.Analyzer#422]
**Context**
Version: 1.0.756
Target Framework: _.NET 7.0_
Language version: _11.0_

**Describe the bug**
Visual Studio will warn that a lot of types cannot be loaded when targeting .NET 7.0

![image](https://user-images.githubusercontent.com/25608596/204237832-e56770a8-19fc-427d-8d3c-9f28c7a6e131.png)

**To Reproduce**
A .NET 7.0 project with latest version of the analyzer. 

**Additional context**
I tried deleting the package folder manually. Cleared the project. Deleted the bin and obj for the whole solution. Rebuild. Etc.
Going back to a previous version of the project still targeting .NET 6.0 the issue is gone. I'm pretty sure it is .NET 7 related and not only my local machine. But can't say for sure, so that is why I am submitting this issue.

**Comment by meziantou** [comment]
This is a common error. Unfortunately, this is not something I can fix as it is not related to my code. I think the error is in Visual Studio. I've pinned an issue with _solutions_ from previous issues: https://github.com/meziantou/Meziantou.Analyzer/issues/423.
