### ISSUE TITLE
Add rule to detect unnecessarily calls to StateHasChanged() in Blazor components

### ISSUE THREAD

**Issue by stiankroknes** [meziantou/Meziantou.Analyzer#424]
**Is your feature request related to a problem? Please describe.**
Get help to detect unnecessarily calls to StateHasChanged() in Blazor components.

**Describe the solution you'd like**
Get a warning when calling StateHasChanged() unnecessarily.

- Handling typical lifecycle events where [ComponentBase](https://github.com/dotnet/aspnetcore/blob/de3019b7dab5b5995942db1fbec6aa466c4af34c/src/Components/Components/src/ComponentBase.cs).
- For [an-asynchronous-handler-involves-multiple-asynchronous-phases](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-7.0#an-asynchronous-handler-involves-multiple-asynchronous-phases) if last invocation in method body is StateHasChanged give warning?
- Routinely handling events, whether synchronously or asynchronously, since [ComponentBase](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase) triggers a render for most routine event handlers.

**Describe alternatives you've considered**
Follow the guidance [aspnetcore-7.0#when-to-call-statehaschanged](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-7.0#when-to-call-statehaschanged).

**Additional context**
- https://learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-7.0#when-to-call-statehaschanged

**Comment by meziantou** [comment]
This rule is not trivial to implement. Detecting the call to `StateHasChanged` is easy. However, you need to understand when a method is called from an event. Also, you need to be sure the method is only called from an event. This makes this rule not trivial to implement.
