### ISSUE TITLE
Publish release notes

### ISSUE THREAD

**Issue by Piedone** [meziantou/Meziantou.Analyzer#431]
**Is your feature request related to a problem? Please describe.**
I'm using v1.0.734 currently and looking to upgrade to v2.0.4. To be able to evaluate whether to do the upgrade and if yes, how, I'd need some pointers on the changes between the two versions (which, judging from the major version change, are significant and breaking).

**Describe the solution you'd like**
Ideally, commits related to versions would be tagged, and there'd be release notes on GitHub detailing the changes between two versions. Hand-edited release notes are not necessary, GitHub can generate release notes with all the pull requests since the previous version.

**Describe alternatives you've considered**
Currently, to see what changed between two versions, the only reliable way I see is checking out [workflow runs](https://github.com/meziantou/Meziantou.Analyzer/actions/workflows/ci.yml) and trying to find one corresponding to the versions I'm looking for, by using the run's time, the title, and ultimately the run's log for hints.

**Additional context**
-

**Comment by meziantou** [comment]
> Currently, to see what changed between two versions, the only reliable way I see is checking out [workflow runs](https://github.com/meziantou/Meziantou.Analyzer/actions/workflows/ci.yml) and trying to find one corresponding to the versions I'm looking for, by using the run's time, the title, and ultimately the run's log for hints.

I publish a version each time a commit is pushed to the main branch (except when only the doc changed). The NuGet package contains the commit id (SHA1) used to build the package. For instance, https://nuget.info/packages/Meziantou.Analyzer/2.0.4 shows 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/509220/211645371-486e57fa-d6fb-43c0-bb4a-86b65db6d963.png">

So, you can compare the commits between 2 versions. No need to check GitHub Actions.

If I have time, I can check how to publish a release each time a package is published from the CI.

> To be able to evaluate whether to do the upgrade and if yes, how, I'd need some pointers on the changes between the two versions

The major change in 2.0.x is the way the analyzer is packaged. Meziantou.Analyzer now multi-targets Roslyn (3.8, 4.2, and 4.4). This feature is supported starting with .NET SDK 6.0.100. So, if you use older SDKs it may not work. That why I prefered to increase the major version.

Why this change? It allows to take advantages of new Roslyn features in analyzers and support new C# 10 / 11 syntaxes.

**Comment by Piedone** [comment]
Thanks for explaining. That's a lot better than what I thought, but still, I think explicit releases and tags (which is what most of the project do) would make this easier to digest.

BTW you can also automate not just publishing to NuGet, but also publishing releases with GitHub Actions: https://github.com/ncipollo/release-action

**Comment by meziantou** [comment]
It's in progress (using `gh release create`): https://github.com/meziantou/Meziantou.Analyzer/pull/432/files

**Comment by Piedone** [comment]
Awesome!

**Comment by meziantou** [comment]
First release https://github.com/meziantou/Meziantou.Analyzer/releases :)

**Comment by Piedone** [comment]
Great, thank you!
