### ISSUE TITLE
MA0006 trigger on string pattern match with `is`

### ISSUE THREAD

**Issue by NickLydon** [meziantou/Meziantou.Analyzer#440]
**Is your feature request related to a problem? Please describe.**
This rule isn't triggered when using pattern matching on a string to compare it to a constant, e.g. `property.Name is "CallerSource"`

**Describe the solution you'd like**
The same check as if it had been `property.Name == "CallerSource"`

**Comment by meziantou** [comment]
I think I would add a new rule to report this case. While this looks similar to MA0006, the code fix is harder to implement, so I may not implement it. It can be easy for `str is "value"` but pattern matching can be much more complex (e.g. `value is { Str: "foo" or "bar" }`). 
Also, I don't think the rule will be enabled by default as there is no code fix. So, you'll need to enable it explicitly in the `.editorconfig` file.

**Comment by NickLydon** [comment]
Thanks for adding it!

> Also, I don't think the rule will be enabled by default as there is no code fix

Do you mean there's no _existing_ code fix, or that it's _impossible_ to automate?

**Comment by meziantou** [comment]
There is no existing code fix. And I don't plan to implement one at the moment as it's unclear how the code should be rewritten for complex patterns.
