### ISSUE TITLE
Consider CA2201 a duplicate of MA0014?

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#460]
Do you consider [CA2201](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201) a partial of full duplicate of MA0014?

Let me know if you want me to update the [comparison page](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md).

**Comment by meziantou** [comment]
Both rules look very similar. Feel free to submit a PR.
