### ISSUE TITLE
More opportunities for MA0020

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#461]
MA0020  could also flag the following cases:

## IEnumerable<T>.All<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
```c#
using System.Linq;
using System.Collections.Generic;

var x = new List<string>();

// Advise to use List<T>.TrueForAll(Predicate<T>) instead
x.All(p => p.StartsWith('a'));
```

## IEnumerable<T>.Any<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
```c#
using System.Linq;
using System.Collections.Generic;

var x = new List<string>();

// Advise to use List<T>.Exists(Predicate<T>) instead
x.Any(p => p.StartsWith('a'));
```

**Comment by meziantou** [comment]
Good suggestion! It will be available in the next version.
