### ISSUE TITLE
New rule: Do not define static fields and auto-properties on a generic type

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#468]
When a static field or auto-property is defined on a generic type, it is not shared between different closed constructed types. This can lead to nice surprises.

For example:
```c#
public class Program
{
    static void Main()
    {
        var executableString = new Executable<string>();
        var executableBool = new Executable<bool>();

        if (!ReferenceEquals(executableString.Execute(), executableBool.Execute()))
        {
            Console.WriteLine("Oops #1");
        }

        if (!ReferenceEquals(Executable<string>.SharedObject, Executable<bool>.SharedObject))
        {
            Console.WriteLine("Oops #2");
        }
    }
}

public class Executable<T>
{
    private static readonly object CostlyObject = CreateCostlyObject();

    public static object SharedObject { get; } = CreateCostlyObject();

    public object Execute()
    {
        return CostlyObject;
    }

    private static object CreateCostlyObject()
    {
        return new object();
    }
}
```

When ran, the code above writes the following to stdout:
```
Oops #1
Oops #2
```

This shows that the costly method ran for both **Executable<string>** and **Executable<bool>**.

You already have **MA0018** that may appear similar on the surface, but it's quite a different beast.
I was surprised that neither this analyzer nor the MS analyzers seem to report this issue.
I could be mistaken though.

I only found such a rule in [Sonar](https://rules.sonarsource.com/csharp/RSPEC-2743).

**Update:**
R# reports a [warning](jetbrains.com/help/resharper/2022.3/StaticMemberInGenericType.html) in the IDE for both static fields and auto-properties. I updated this issue accordingly.

**Comment by drieseng** [comment]
@meziantou, for properties this can be trickier as they can be implementing an interface (either explictly or implicitly).

**Comment by meziantou** [comment]
If the rule exists in Sonar, why do you want to duplicate it in this analyzer? What would be the added value?

**Comment by drieseng** [comment]
I don't use Sonar, just found the rule by accident.

**Comment by meziantou** [comment]
What prevent you from adding the sonar analyzer to your projects? I think it's better to use existing rules from well-supported analyzers rather than duplicate them. I don't want to add maintenance cost to this project if it's not needed.

**Comment by drieseng** [comment]
@meziantou, you're right. Sorry for the noise.
