### ISSUE TITLE
MA0018 should be consider similar to CA1000

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#469]
Right now, **MA0018** is considered to be an equivalent of **CA1000**.
However, the latter can also be configured to apply to the non-public API surface.

I propose to move this to the "Similar rules" section, or update **MA0018** to also support running against the non-public API surface.

**Comment by meziantou** [comment]
Let's start by updating the documentation. Do you want to submit a PR?

**Comment by drieseng** [comment]
I'll do that some time this week.
