### ISSUE TITLE
2.0 Changelog?

### ISSUE THREAD

**Issue by SebastianStehle** [meziantou/Meziantou.Analyzer#472]
Hi,

do you have a changelog for 2.0? I am curious what you have changed.

**Comment by meziantou** [comment]
You can read the comment in the following issue to get info about the v2: https://github.com/meziantou/Meziantou.Analyzer/issues/431#issuecomment-1377766577

For newer versions, the release notes are available in Github Releases https://github.com/meziantou/Meziantou.Analyzer/releases
