### ISSUE TITLE
MA0009 is not reported for GeneratedRegexAttribute

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#485]
I supposed "we" want to encourage users to also specify a timeout when using the **GeneratedRegexAttribute** (via **MatchTimeoutMilliseconds**).

PS. the example on the **MA0110** doc page is not correct as the attribute is no longer called **RegexGenerator(Attribute)**.

**Comment by meziantou** [comment]
MA0009 and MA0110 both support `GeneratedRegexAttribute`, but the documentation needs to be updated.

**Comment by meziantou** [comment]
Maybe there is an issue with MA0009 because it doesn't scan generated code. As the source generator adds the `[GeneratedCode]` attribute, the method may be excluded from analysis. I'll have a look.
