### ISSUE TITLE
Document CA1822 as equivalent of MA0036, MA0038 and MA0041

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#488]
If I'm not mistaken, **CA1822** is an equivalent of **MA0036**, **MA0038** and **MA0041**.
When confirmed, I'll update the doc accordingly.

**Comment by meziantou** [comment]
The 3 rules are deprecated in favor of CA1822 as stated in the documentation. So, you can add them to the comparison-with-other-analyzers.md if you want.

**Comment by drieseng** [comment]
MA0036 is not (documented as being) deprecated. Should it be as well?

**Comment by meziantou** [comment]
Indeed, MA0036 is not deprecated. But, I don't think this is an equivalent of CA1822.

- MA0036 reports types that can be static
- CA1822, MA0038, and CA0041 reports members that can be static

**Comment by drieseng** [comment]
Indeed, it's [**CA1052**](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1052) that is equivalent or at least similar to **MA0036**. Which category matches best?

**Comment by meziantou** [comment]
MA0038 and MA0041 are deprecated because CA1822 supports more cases. So, there are similar but not equivalent. And it is recommended to use CA1822.

I don't know the differences between MA0036 and CA1052. I only know that CA1052 is configurable which is not the case of MA0036.

**Comment by drieseng** [comment]
I'll mark them all as similar them. I'll submit a PR later this weekend or next week.
