### ISSUE TITLE
Unnecessary [MA0005] Use Array.Empty<T>

### ISSUE THREAD

**Issue by nj0yeh** [meziantou/Meziantou.Analyzer#500]
**Context**
Rule identifier: _MA0005_
Target Framework: _.NET 6.0_
Language version: _11.0_

**Describe the bug**
Using the attributes `[Consumes]` and `[Produces]` from Microsoft.AspNetCore.Mvc raises this exception:
`[MA0005] Use Array.Empty<T>()`
It does not really make sense in this context.

**To Reproduce**
Code or steps to reproduce the behavior:

````c#
using Microsoft.AspNetCore.Mvc;

[Consumes("application/json")]
[Produces("application/json")]
public class MyController
{
}
````

**Additional context**
The attribtues are declared like this:
````c#
public ConsumesAttribute(string contentType, params string[] otherContentTypes)
```` 

You can suppress the warning by using the code, but this should not be the way to go:
````c#
[Consumes("application/json", null!)]
[Produces("application/json", null!)]
````

**Comment by meziantou** [comment]
I think this is fixed a few versions ago. Do you use the latest version of the package?

**Comment by nj0yeh** [comment]
Sorry, you are completely right, I was referencing an old version. Updating to the latest version hides the warning.
