### ISSUE TITLE
skip_local_functions is not respected when counting method lines

### ISSUE THREAD

**Issue by hankovich** [meziantou/Meziantou.Analyzer#561]
### Version of the Meziantou.Analyzer NuGet package

2.0.66

### Rule Identifier

MA0051

### Target Framework

net8.0

### C# Language version

C# 12

### Description

I receive a lot of `MA0051: Method is too long` for short methods with lots of local functions. `skip_local_functions = true` doesn't work. It looks like it's not respected 

### Reproduction Steps

Minimal code:

```c#
code to reproduce the error
```

**Comment by meziantou** [comment]
The `skip_local_functions` options was only supported when counting statement, not lines. https://github.com/meziantou/Meziantou.Analyzer/pull/562 adds support when counting lines.

**Comment by hankovich** [comment]
Thank you for the ultra fast reply and fix. I use your package for two days, but already feel that it's pure gold
