### ISSUE TITLE
MA0124 config: allow naming conventions

### ISSUE THREAD

**Issue by molszews** [meziantou/Meziantou.Analyzer#572]
Existing codebase I'm working one is pretty large and type collisions tend to happen quite often and are difficult to notice. Unfortunatelly maintaing list of every used parameter name is at least tricky - we would need to keep track of every introduced parameter and distribute the list across different repos, also making sure list is always up to date.

Instead of that we could agree on some conventions, that way we could distribute set of these and also require every log parameter to mach exactly one convention described in the rule config file. We could use regexp or something similar to describe the pattern, e.g. *Obj should be mapped as Object, etc.

**Comment by meziantou** [comment]
I'm adding a new opt-in rule to ensure all parameters are configured https://github.com/meziantou/Meziantou.Analyzer/compare/ma0135

I'm not sure about the regex. In the code I read or write, I haven't seen names with prefix or suffix to indicate the type. So, I'm not sure this is a common practice. Maybe I can revisit this if you can provide some examples showing that it's common to have name patterns matching a specific type.
