### ISSUE TITLE
Consider Using Attributes for Log Field Definitions

### ISSUE THREAD

**Issue by JasonBock** [meziantou/Meziantou.Analyzer#574]
**Is your feature request related to a problem? Please describe.**
This is related to [this article](https://www.meziantou.net/roslyn-analyzer-to-check-the-types-of-structured-log-messages.htm).

**Describe the solution you'd like**
Instead of using an additional file, the configuration would be done with attributes. That way, you could do something like this:

```csharp
[assembly: StructuredLogField("Name", typeof(string))]
```

That way, I avoid mistyping the type name. Multiple types could also be supported:

```csharp
[assembly: StructuredLogField("Count", typeof(int), typeof(long))]
```

There is an issue of, how does `StructuredLogFieldAttribute` get defined in an analyzer project such that consumers could use it? One thought is to add an incremental generator that emits the attribute type, and then it should be available for consumers. Not sure if that would work though.

Also, now the analyzer would have to find all instances of `[StructuredLogField]` in the project first, and then determine correct log field usage. That may be dicey, if not infeasable.

**Comment by meziantou** [comment]
Supporting the attribute is not too complicated, at least if the attribute is only valid in the current assembly. You can see how to add it to your project in this PR: https://github.com/meziantou/Meziantou.Analyzer/pull/578.

However, I'm not sure what's the best way to add it to the project automatically. There are multiple solutions:
- Using a source generator
- Adding a file to the compilation using an MSBuild property. The cs file would be in the package. (`<Compile Include="attributes.cs" Visible="False" />`)
- Create another package (`Meziantou.Analyzer.Attributes` / `Meziantou.Analyzer.Annotations`, similar to `JetBrains.Annotations`) => Harder to discover, but doesn't impact compilation
- Let the user add the attributes manually

**Comment by meziantou** [comment]
I choose the package approach. So, there is a new package named Meziantou.Analyzer.Annotations.

**Comment by JasonBock** [comment]
Wow, that was quick :). Open source and community in action, I love it!
