### ISSUE TITLE
MA0124: support for LoggerMessage attribute

### ISSUE THREAD

**Issue by cheesi** [meziantou/Meziantou.Analyzer#575]
**Is your feature request related to a problem? Please describe.**
The rule MA0124 currently doesn't support the `LoggerMessageAttribute`.

**Describe the solution you'd like**
Also detect type mismatches, when the `LoggerMessageAttribute` is used.

**Describe alternatives you've considered**
None

**Additional context**
Already works for the `LoggerMessage.Define` without source code generator.
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/5590254/04ea6e54-eb61-4413-b429-d0651d2c1524)

However doesn't work for the `LoggerMessageAttribute`:
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/5590254/6c05edf3-0182-4d4d-a419-015872c69284)

Sample repo: https://github.com/cheesi/Meziantou.Analyzer.Test/tree/main

**Comment by meziantou** [comment]
On my machine, the error is correctly reported in the generated code. The analyzer doesn't check the attribute, but the generated code.

Can you confirm the warning is reported on your side?

<img width="1127" alt="image" src="https://github.com/meziantou/Meziantou.Analyzer/assets/509220/d31c5013-937f-4448-9196-2e8e3aaa8c23">

**Comment by cheesi** [comment]
Hey!

Yes I can confirm now, that there are three warnings now:
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/5590254/4a979866-a894-4305-8915-315705e319e2)

I could swear, that I had only two warnings yesterday...
Strange. Maybe VS restart played into that.

Then case closed. (or consider it as a usability thing, to add the warning on the attribute / method definition)

**Comment by meziantou** [comment]
VS can be confusing sometimes... I think it also depends on the setting "Run Background analysis for" which may be switched to "Entire Solution" instead of opened documents.

You can get consistent results by building using the CLI (dotnet build).

**Comment by meziantou** [comment]
For the usability, it would report the generated code and the attribute. Maybe this could be confusing.

I would accept a PR, but I'm not sure I will do it myself.
