### ISSUE TITLE
MA0042 asks to make infinite recursion

### ISSUE THREAD

**Issue by hankovich** [meziantou/Meziantou.Analyzer#587]
### Version of the Meziantou.Analyzer NuGet package

2.0.74

### Rule Identifier

MA0042

### Target Framework

net8.0

### C# Language version

C# 12

### Description

It should not request to use async version if we're already in async version

### Reproduction Steps

```c#
int Foo() => 5;

Task<int> FooAsync() => Task.FromResult(Foo()); // <- MA0042 use FooAsync instead
```

**Comment by meziantou** [comment]
There are legit cases to use the async version even in the async method (recursion). So, I don't think it's ok to detect this case.

I suggest discarding the diagnostic using an attribute or a directive.
