### ISSUE TITLE
New rule: Do not call ToList on concurrentdictionary.

### ISSUE THREAD

**Issue by SebastianStehle** [meziantou/Meziantou.Analyzer#594]
**Is your feature request related to a problem? Please describe.**
I was just having issues with that: https://stackoverflow.com/questions/41038514/calling-tolist-on-concurrentdictionarytkey-tvalue-while-adding-items

Calling ToList on concurrent dictionary is no safe. There are problem other collections as well.

Would be great to have an analyzer for that. Should even be an error in the default settings.

**Comment by meziantou** [comment]
The issue may occur for any method that uses an interface (e.g. `ICollection`) on a type that is documented to not be thread-safe on these interfaces. I've already explained a similar issue on a custom collection: https://www.meziantou.net/investigating-a-crash-in-enumerable-lastordefault.htm

<img width="653" alt="image" src="https://github.com/meziantou/Meziantou.Analyzer/assets/509220/e97989d6-bd97-4e2a-a73d-8de805a35502">

Also, all these calls are valid if the code is not multi-threaded or correctly synchronized.

So, I'm not sure about this rule as there will be lots of false-positive.
