### ISSUE TITLE
MA0008 code fix adds wrong LayoutKind

### ISSUE THREAD

**Issue by k3min** [meziantou/Meziantou.Analyzer#595]
https://github.com/meziantou/Meziantou.Analyzer/blob/07a67bf07950559856bec65eec956bffd50b58ab/src/Meziantou.Analyzer/Rules/UseStructLayoutAttributeFixer.cs#L42

Should be `LayoutKind.Sequential`.

**Comment by meziantou** [comment]
Thanks for reporting the issue! Do you want to submit a PR?

**Comment by k3min** [comment]
#596
