### ISSUE TITLE
MA0048 false positives since 2.0.88?

### ISSUE THREAD

**Issue by bdovaz** [meziantou/Meziantou.Analyzer#607]
### Version of the Meziantou.Analyzer NuGet package

2.0.91

### Rule Identifier

MA0048

### Target Framework

.net7

### C# Language version

C# 11

### Description

@meziantou Since tonight's release, this warning will be displayed for all classes of the project.

### Reproduction Steps

1. Create a console project.
2. Install 2.0.91 NuGet package.
3. See the warning in Program.cs class.

Example project:

[ConsoleApp11.zip](https://github.com/meziantou/Meziantou.Analyzer/files/12780211/ConsoleApp11.zip)

At the moment I downgrade to 2.0.87 which I think is the last one that does not have this problem.

**Comment by robertodalmonte** [comment]
I confirm...MA0048 everywhere since the latest update:
<PackageReference Include="Meziantou.Analyzer" Version="2.0.91">

No problems with 2.0.87

**Comment by lachezar-gizdov** [comment]
Same here. No problems with 2.0.87

**Comment by credfeto** [comment]
Same here.  This complains that the class `Ping` doesn't doesn't match `Ping.cs` https://github.com/funfair-tech/BuildBot/blob/main/src/BuildBot.ServiceModel/GitHub/Ping.cs  with 2.0.91.  Previous release version 2.0.87 was fine.  

Sample PR for update: https://github.com/funfair-tech/BuildBot/pull/133

**Comment by RaduTerec** [comment]
Same here. There were no problems with 2.0.87.

Tested with .net 7.0.111 on Ubuntu 22.04

**Comment by meziantou** [comment]
Should be fixed in the latest version

**Comment by bdovaz** [comment]
Thanks @meziantou!

**Comment by credfeto** [comment]
Thanks @meziantou
