### ISSUE TITLE
MA0056 - Specify how this can be resolved by making the class sealed

### ISSUE THREAD

**Issue by ruudschouten** [meziantou/Meziantou.Analyzer#609]
I run into [MA0056](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0056.md#ma0056---do-not-call-overridable-members-in-constructor) every so often, and just stumbled upon #30 which states that this rule is skipped when the class is sealed.

I would like to suggest elaborating in the markdown file for MA0056 that this can be resolved by making your class sealed, and why this is a suitable fix.

I am specifically asking for the reasoning why this is fixed, since a similar rule; [CA2214](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2214) does not state that this can be resolved by making your class sealed.
I assumed this was the case since it would make sure your class cannot be inherited, meaning virtual methods cannot exist in your class, but this can still call methods that are not implemented in any class that you inherit from.

**Comment by meziantou** [comment]
When a class is sealed, you cannot create a class that inherits from this class and override virtual members. So, when you call a virtual member from a sealed class, you know exactly which implementation is called and you are sure all constructors are called correctly. So, there is no reason to report a diagnostic.

**Comment by meziantou** [comment]
> I am specifically asking for the reasoning why this is fixed, since a similar rule; [CA2214](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2214) does not state that this can be resolved by making your class sealed.

From the doc: The constructor of an **unsealed** type calls a virtual method defined in its class.
