### ISSUE TITLE
Flag MA0046 as duplicate of CA1003

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#618]
Is **MA0046** a duplicate of **CA1003**, or more an equivalent?

**MA0046**: [doc](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0046.md) and [source](https://github.com/meziantou/Meziantou.Analyzer/tree/main/src/Meziantou.Analyzer/Rules/UseEventHandlerOfTAnalyzer.cs)
**CA1003**: [doc](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1003) and [source](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UseGenericEventHandlerInstances.cs).

**Comment by meziantou** [comment]
The rules are identical, except that CA1003 only reports for public types by default. You can configure the rule to report on all types.
