### ISSUE TITLE
Problems with MA0137 and Program.cs

### ISSUE THREAD

**Issue by philippedurocher** [meziantou/Meziantou.Analyzer#636]
### Version of the Meziantou.Analyzer NuGet package

2.0.102

### Rule Identifier

MA0137 

### Target Framework

dotnet 8 rc2

### C# Language version

C# 12

### Description

In my Blazor app, the Program.cs is triggering this error

`..\Program.cs(1,1,115,1): error MA0137: Method returning an awaitable type must use the 'Async' suffix`

I used a #pragma warning disabled to remove the warnings, but is there another way? 

Thank you.

### Reproduction Steps

Set editorconfig variables related to MA0137 to warning & use Blazor.

**Comment by meziantou** [comment]
> but is there another way?

Yes, fixing the code :)
