### ISSUE TITLE
CA1814: Prefer jagged arrays over multidimensional rule (code quality)

### ISSUE THREAD

**Issue by alirzasahb** [meziantou/Meziantou.Analyzer#638]
- Rule: CA1814: Prefer jagged arrays over multidimensional
- Link to the equivalent rule documentation: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1814

What are your thoughts?

**Comment by meziantou** [comment]
I'm not sure to understand what you want. Is it to suggest a duplicated rule? If so, can you please provide the equivalent MA rule? If not, can you provide more info?

**Comment by alirzasahb** [comment]
Hey Gérald, Thanks for Your Response
So, What I propose is request a new rule equivalent to Prefer jagged arrays over multidimensional (CA1814).

**Comment by meziantou** [comment]
Why do you expect a new rule in this analyzer instead of using the existing rule provided by .NET? What's wrong with the built-in rule?

**Comment by alirzasahb** [comment]
My bad, CA1814 Severity Level In Roslyn Analyzer was set to “None” in my environment.
Thanks For Your Patience.
