### ISSUE TITLE
MA0008

### ISSUE THREAD

**Issue by drieseng** [meziantou/Meziantou.Analyzer#649]
### Version of the Meziantou.Analyzer NuGet package

2.0.110

### Rule Identifier

MA0008

### Target Framework

net7.0

### C# Language version

C# 11

### Description

I'm sure this worked before, but right now the **MA0008** diagnostic is no longer reported for a struct that is not decorated with a **StructLayoutAttribute**.

The rule is effecitvely enabled:

![image](https://github.com/meziantou/Meziantou.Analyzer/assets/312863/7af98740-6d6a-4688-ac2e-1d38baa9cfae)

### Reproduction Steps

Minimal code:

```c#
public struct Box
{
}
```

**Comment by meziantou** [comment]
The rule only reports [blittable structures](https://learn.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types?WT.mc_id=DT-MVP-5003978) with many fields / properties as this is where the attributes is useful.

````
struct A { } // ok
struct A { public int A; } // ok
struct A { public int A; public string B } // Auto by default as string is not blittable

struct A { public int A; public int B; } // report diagnostic
````

**Comment by drieseng** [comment]
@meziantou, thanks for the clarification. Sorry for the noise.
