### ISSUE TITLE
MA0048 - allow the partial class keyword for multi-files

### ISSUE THREAD

**Issue by davidkallesen** [meziantou/Meziantou.Analyzer#667]
When I have a file like:
`MyViewModel.cs` with the `class MyViewModel` - then the MA0048 is great rule.

But if I extend `class MyViewModel` with the partial keyword => `partial class MyViewModel` and add a new file like `MyViewModel_Commands.cs` with the same class declaration `partial class MyViewModel`. When I have make a suppression in both files.

So it will be very nice, if the MA0048 extended with more compliant's as:

```c#
// filename: Foo.cs
partial class Foo // compliant
{
}

// filename: Foo_Bar.cs
partial class Foo // compliant
{
}

// filename: Foo{T}.cs or FooOfT.cs or Foo`1.cs
partial class Foo<T> // compliant
{
}

// filename: Foo{T}_Bar.cs or FooOfT_Bar.cs or Foo`1_Bar.cs
partial class Foo<T> // compliant
{
}
```

Note: I don't know if the underscore is a well known standard in filename for partial classes. But I/we use it alot for WPF/MVVM code.
As a small example can be found here in the project [atc-installer](https://github.com/atc-net/atc-installer/tree/main)
- [MainWindowViewModel.cs](https://github.com/atc-net/atc-installer/blob/main/src/Atc.Installer.Wpf.App/MainWindowViewModel.cs)
- [MainWindowViewModel_Commands.cs](https://github.com/atc-net/atc-installer/blob/main/src/Atc.Installer.Wpf.App/MainWindowViewModel_Commands.cs)
- [MainWindowViewModel_LogicBase.cs](https://github.com/atc-net/atc-installer/blob/main/src/Atc.Installer.Wpf.App/MainWindowViewModel_LogicBase.cs)

**Comment by meziantou** [comment]
There is a difference between `_` and `.`/`{`/`` ` ``, the former is a valid identifier character.

```
// file: Sample_foo.cs
class Sample {} // should it be valid?
class Sample_foo {} // should it be valid?
class Sample_bar {} // should it be valid?
```

Maybe the best solution is to add configuration for this rule, so you can provide the valid separators.

**Comment by davidkallesen** [comment]
I am not sure what the best solution it, but it sounds like a good ide with a configuration for the seperator, as long as the underscore is default for the rule :-) (to fit my use-case)

And just to be clear on my use-case; I never user underscore for my class names. And it a good seperator for the filename; It gives a good "listing" in the file-explore - with the master file first.

And the my anwser for:
```C#
// file: Sample_foo.cs
class Sample {} // should it be valid?  => No, only if `partial class` then yes
class Sample_foo {} // should it be valid?  => Yes, becase of the filename match
class Sample_bar {} // should it be valid?  => No
```
