### ISSUE TITLE
MA0124 Support case insensitive matching mode

### ISSUE THREAD

**Issue by latop2604** [meziantou/Meziantou.Analyzer#668]
The rule [MA0124](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0124.md) is really useful. (Others too but it's not the point).

It would be nice to have a way (csproj property maybe) to enable a case insensitive matching mode in order to not have to duplicate all parameter name variations in the LoggerParameterTypes.txt.

In my case, all parameters from my log message are translated in camelCase. So `MyPropertyId` and `myPropertyId` will be a single one at the end. But `myPropertyId` and `mypropertyid` will stay as two distinct properties.
The full case insensitive would be enough, but camel case matching mode would be even better.

Voila voila,
Have a nice day

**Comment by latop2604** [comment]
It could also be per line configuration like javascript regex flag notation `/\w+\s/gis;`

**Comment by meziantou** [comment]
- Is it an issue because the parameters are not normalized in the code? In this case, would it be better to provide a code fix to update all log parameters in the code?
- Should the case-sensitivity be per parameter? Or should it be global?

**Comment by latop2604** [comment]
> Should the case-sensitivity be per parameter? Or should it be global?
Why not both? Master project property and/or per param. Both would fit my needs

> Is it an issue because the parameters are not normalized in the code? In this case, would it be better to provide a code fix to update all log parameters in the code?
Even if the existing source code is normalised, if someone add an existing param but with a different casing, it will not trigger any warning if not already exactly defined in LoggerParameterTypes

**Comment by meziantou** [comment]
> Why not both? Master project property and/or per param. Both would fit my needs

Everything's possible, but time is not infinite. I prefer keeping the scope small if it fits the need.

> Even if the existing source code is normalised, if someone add an existing param but with a different casing, it will not trigger any warning if not already exactly defined in LoggerParameterTypes

You can enable `MA0135` to report all unconfigured parameters.

**Comment by latop2604** [comment]
`MA0135` is a nice alternative. Thx.
