### ISSUE TITLE
Analyze usage of CultureInfo ctor

### ISSUE THREAD

**Issue by TheR00st3r** [meziantou/Meziantou.Analyzer#683]
**Is your feature request related to a problem? Please describe.**
In your blog you wrote an article about the difference between ctor `new CultureInfo` and `CultureInfo.GetCultureInfo`.
If CultureInfo never gets updated `CultureInfo.GetCultureInfo` should be used. If `new CultureInfo` is used but CultureInfo is never updated there could be a warning.

**Comment by meziantou** [comment]
`new CultureInfo` is almost always wrong. I think it's easier to use the Microsoft.CodeAnalysis.BannedApiAnalyzers package to disallow the symbol. Also, it's hard to detect when the CultureInfo is edited or not as it can be made in multiple methods.
