### ISSUE TITLE
[Question]: Is there any way to enable all rules in this package?

### ISSUE THREAD

**Issue by edumserrano** [meziantou/Meziantou.Analyzer#688]
There are some rules that are disabled by default like [MA0032](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0032.md) and I was wondering if there was way to enable all of the rules without having to do it rule by rule?

I have `dotnet_analyzer_diagnostic.severity = warning` so that all rules by default are reported as `warnings` but that doesn't seem to apply if the rule is disabled by default. 

One of the reasons I'm asking is that, if possible, this is not only helpful to quickly enable the disabled rules but it also means when you add new rules and they are disabled by default I still get them applied to my project and I can make a decision of whether or not I want to disable that one. Otherwise you could add a new rules that I'm actually interested and I won't find out unless I pay attention to release notes/updates to the docs.

Is there any way to achieve this?

**Comment by edumserrano** [comment]
I wasn't finding any information regarding this before creating the issue but I eventually stumbled upon dotnet/roslyn#47046. It seems that by design this is not yet possible:

> Entries to configure multiple analyzer rules at once only apply to rules that are enabled by default. Analyzer rules that are marked as disabled by default in the analyzer package must be enabled through explicit dotnet_diagnostic.<rule ID>.severity = <severity> entries.[^1]

[^1]: [Set rule severity of multiple analyzer rules at once in an EditorConfig file](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file)

I guess this issue can be closed unless there's some kind of workaround that you provide for this package?

**Comment by meziantou** [comment]
You must enable them rule by rule in the editorconfig file. You can find the list of rules to enabled in this page: https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/README.md (column "Is enabled").
