### ISSUE TITLE
Remove rules with a Roslyn Equivalent

### ISSUE THREAD

**Issue by TimmyMC** [meziantou/Meziantou.Analyzer#702]
**Is your feature request related to a problem? Please describe.**
Excuse me if this is a dumb question, but why are rules (~30) that have a Roslyn equivalent not removed? 
Is that not just bloat causing extra analysis time or polluting the .editorconfig file with always disabled rules?

**Describe the solution you'd like**
A slimmer version of this package.

**Comment by meziantou** [comment]
The similar rules are documented here: https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md. Some rules are not strictly identical, so be careful when disabling rules. If some rules are missing in the list, please fill in an issue or submit a PR.

It's a hard change to remove the rules. This doesn't mean it won't happen, but the timeline should not be too fast. The version that introduces this change must be a major version.

For the editorconfig, I strongly recommend creating a coding standard package to _hide_ the editorconfig files and more from your projects.

- Post: https://www.meziantou.net/sharing-coding-style-and-roslyn-analyzers-across-projects.htm
- Example: https://github.com/meziantou/Meziantou.DotNet.CodingStandard

**Comment by TimmyMC** [comment]
Thanks for the reply
