### ISSUE TITLE
MA0010 - Should be deprecated in favor of CA1018

### ISSUE THREAD

**Issue by viceroypenguin** [meziantou/Meziantou.Analyzer#705]
- Rule: MA0010
- Link to the equivalent rule documentation: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1018

**Comment by meziantou** [comment]
Thanks for reporting it. I've added the rule to the documentation page https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md

Fixed by https://github.com/meziantou/Meziantou.Analyzer/commit/c3e2bbeffd0cd76b63057c88bdbf2d2fcd349149
