### ISSUE TITLE
MA0047 - Should be deprecated in favor of CA1050

### ISSUE THREAD

**Issue by viceroypenguin** [meziantou/Meziantou.Analyzer#706]
- Rule: MA0047
- Link to the equivalent rule documentation: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1050

**Comment by meziantou** [comment]
Thanks for reporting it. The rule is already documented as duplicated: https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md

Feel free to disable the rule in your editorconfig and use CA1050 instead.

**Comment by viceroypenguin** [comment]
I was looking at the list of analyzers in the editor. 

MA0047 does not show as deprecated:
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/1992555/983cbb55-ce19-431e-a1d8-e66bbf348dd8)

while others are marked as deprecated.
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/1992555/dfbe4ec5-6234-4d91-8110-bc2d8611f774)


Should I open a ticket to review the analyzer names to mention deprecation there to match the comparison with other analyzers list? I can do a quick review if it would help.

**Comment by meziantou** [comment]
There is no clear deprecation plan yet for duplicated rules. The ones marked as deprecated in the error message are buggy with some new C# features. So, there is a clear need for the user to migrate to the CA equivalent.
Other rules may be duplicated, but there is no known bug and the impact on build time is negligeable. So, you can keep both rules or choose to disable one of them.

**Comment by viceroypenguin** [comment]
Thanks for the info! And thanks for the analyzers!
