### ISSUE TITLE
Rule for consistent formatting of comments

### ISSUE THREAD

**Issue by bdovaz** [meziantou/Meziantou.Analyzer#712]
I would like if there are comments of this type:

```csharp
//TEST COMMENT
```

```csharp
//Test comment
```

Should be:

```csharp
// Test comment
```

That is to say, that neither a comment in capital letters nor without space is ok.

My wishlist would be the 2 but if you have to prioritize one it would be the one that has to have a space after //.

**Comment by meziantou** [comment]
You can use StyleCop and the [SA1005](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1005.md) rule to ensure that single line comments start with a single space. I don't think there is a reason to duplicat the rule into this project.
