### ISSUE TITLE
MA0158 docs error

### ISSUE THREAD

**Issue by evgenij-hash** [meziantou/Meziantou.Analyzer#724]
### Version of the Meziantou.Analyzer NuGet package

2.0.153

### Rule Identifier

MA0158 

### Target Framework

net9.0

### C# Language version

c# 11

### Description

https://github.com/meziantou/Meziantou.Analyzer/blob/ef8775e7d807df159833a27e0a74a6c2281288f3/docs/Rules/MA0158.md?plain=1#L14

Should be:

`lock (_lock)`

**Comment by meziantou** [comment]
Thanks!

fixed by 162232f53be59b7e880e61dacbdae862978f2ad7
