### ISSUE TITLE
MA0034 missing from docs#readme ?

### ISSUE THREAD

**Issue by fforjan** [meziantou/Meziantou.Analyzer#727]
### Version of the Meziantou.Analyzer NuGet package

main branch

### Rule Identifier

MA0034

### Target Framework

web portal

### C# Language version

N/A

### Description

On the doc page : 
![image](https://github.com/meziantou/Meziantou.Analyzer/assets/601810/9fcbecb0-999e-4863-9065-71e36bd1bec9)

### Reproduction Steps

N/A

**Comment by meziantou** [comment]
The readme is generated, so it's accurate! The MA0034 rule has been removed a long time ago.
