### ISSUE TITLE
Analysis for 'prefer "is null" instead of "== null" on reference types'

### ISSUE THREAD

**Issue by SteveDunn** [meziantou/Meziantou.Analyzer#733]
This is not related to a problem, but rather a request for a new analysis rule.

The rule spots potential issues with using `== null` for reference types.
Such issues are where the type's `==` operators are overridden, or, if they later become overloaded, they can cause compilation errors with ambiguous operator == methods ([such an issue was found in System.Text.Json](https://github.com/dotnet/runtime/pull/103565))

I'm happy to add the analysis rule.

**Comment by meziantou** [comment]
I think you are referring to the 2 following rules:
- https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0141.md
- https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0142.md

If so, you need to enable them manually in the editorconfig file. There are disabled by default as it's very verbose in existing project and may not bring much value.

**Comment by SteveDunn** [comment]
Thank you @meziantou - that is exactly it! Keep up the great work, and let me know if there's anything I can lend a hand with in this great repo!
