### ISSUE TITLE
Add analyzer when switch is not exhaustive for enumerations

### ISSUE THREAD

**Issue by skarllot** [meziantou/Meziantou.Analyzer#739]
**Is your feature request related to a problem? Please describe.**
Every switch (expression) on enumeration values should handle all possible values of enumeration even when a default case is defined.

**Describe the solution you'd like**
Warning stating that switch is not exhaustive.

**Describe alternatives you've considered**
Analyzer can be disabled by default.

**Additional context**
Should cover switch expressions and switch statements.

**Comment by meziantou** [comment]
It looks very similar to [IDE0010](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0010?WT.mc_id=DT-MVP-5003978). What is not covered by the builtin rule? Could you provide an example?

**Comment by skarllot** [comment]
Odd it is not triggered for me, and I think this analyzer does not enforce when switch has a default case.

**Comment by meziantou** [comment]
I'm not sure what is actually required to enable it, but adding `<AnalysisLevel>latest-all</AnalysisLevel>` to the csproj should enable ide0010.

![image](https://github.com/meziantou/Meziantou.Analyzer/assets/509220/73883e48-66be-440d-b22e-cea4bab8e4d3)

**Comment by skarllot** [comment]
I think that it is enough, thank you
