### ISSUE TITLE
New rule: StringBuilder.AppendJoin

### ISSUE THREAD

**Issue by meziantou** [meziantou/Meziantou.Analyzer#74]
````c#
sb.Append(string.Join(',', new [] { "a", "b" }));
````

Should be:

````c#
sb.AppendJoin(',', new [] { "a", "b" });
````

**Comment by AraHaan** [comment]
Wait stringbulder can do that?

**Comment by meziantou** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.appendjoin?view=netcore-3.1

**Comment by 0liver** [comment]
@AraHaan It's a new method [since .NET Core 2.0](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.appendjoin?view=netcore-3.1#:~:text=.-,net%206%20and%20other%20versions,-Table%207).
