### ISSUE TITLE
error MA0115 auto generate file

### ISSUE THREAD

**Issue by EngRajabi** [meziantou/Meziantou.Analyzer#741]
### Version of the Meziantou.Analyzer NuGet package

2.0.160

### Rule Identifier

MA0115

### Target Framework

net8.0

### C# Language version

C# 12

### Description

error auto generate file. ignore *.g.cs
![image](https://github.com/user-attachments/assets/674e0dd6-531c-4bd2-a2f7-416848a176a1)

### Reproduction Steps

Minimal code:
_No response_

**Comment by meziantou** [comment]
I'm not sure to understand your issue. Can you provide a minimal repro code and explain the current and expected behaviors?

Note that MA0115 must check the generated code as it analyze the C# code generated by Razor.

**Comment by EngRajabi** [comment]
I have a server-side Blazor project that gives this error on one of the automatically generated files.

**Comment by meziantou** [comment]
The rule checks the code generated by Blazor and the code written manually to detect invalid properties. So, it's expected to get errors in `.g.cs` files.
