### ISSUE TITLE
Exclude namespace rule MA0048

### ISSUE THREAD

**Issue by migueloliveiradev** [meziantou/Meziantou.Analyzer#746]
### Version of the Meziantou.Analyzer NuGet package

2.0.163

### Rule Identifier

MA0048

### Target Framework

net8.0

### C# Language version

C# 12

### Description

Hello, I want to keep the [MA0048](https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0048.md) rule in my project, can you delete a namespace

The description setting of the rule mentions something superficial about this, which would be the `dotnet_diagnostic.MA0048.excluded_symbol_names`

Fix numerous tests to reproduce, but I keep getting warning in build

`C:\Users\Miguel Oliveira\source\repos\migueloliveiradev\living\Living.Infraestructure\Migrations\2024_07_27_15_05_AddIdentity.cs(6,14): warning MA0048: File name must match type name (https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0048.md)
`

Possibilities tested in .editorconfig:
- `dotnet_diagnostic.MA0048.excluded_symbol_names = Living.Infraestructure.Migrations.*`
- `dotnet_diagnostic.MA0048.excluded_symbol_names = Living.Infraestructure.Migrations.**.cs`
- `dotnet_diagnostic.MA0048.excluded_symbol_names = T:*Migrations`
- `dotnet_diagnostic.MA0048.excluded_symbol_names = *Migrations`

I thought of some possibilities to solve this

- better understand how the `excluded_symbol_names` works 
- always keep adding `#pragma warning disable MA0048`, something I didn't want

### Reproduction Steps

Minimal code:

file: Living.Infraestructure\Migrations\2024_07_27_15_05_AddIdentity.cs

```c#
namespace Living.Infraestructure.Migrations;

public class AddIdentity
{
    //code ...
}
```

**Comment by meziantou** [comment]
You have multiple ways to disable the rule for specific files:

Note that the full symbol name in your example is `T:Living.Infraestructure.Migrations.AddIdentity`. The wildcard pattern must match the full symbol.

````
[*.cs]
dotnet_diagnostic.MA0048.excluded_symbol_names = *.Migrations.*
````

````
[*.cs]
dotnet_diagnostic.MA0048.excluded_symbol_names = T:Living.Infraestructure.Migrations.*
````

Or you can use the editorconfig features to disable the rule for a folder

````
[Migrations/*.cs]
dotnet_diagnostic.MA0048.severity = none
````

**Comment by migueloliveiradev** [comment]
Thanks
