### ISSUE TITLE
Documentation conflicts

### ISSUE THREAD

**Issue by LiorBanai** [meziantou/Meziantou.Analyzer#753]
Hi.
the following documentation suggest use `FormattableString.Invariant`

https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0076.md

but them MA011 suggest to replace `FormattableString` with  `string.Create`

https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0111.md

so which one is the better option (String.Create seems to have better performances so maybe MA0076 is obsolete)?

**Comment by meziantou** [comment]
MA0076 detect usage of implicit culture-specific conversion to string.
If you apply the fix to use `FormattableString.Invariant` and you are using a recent version of .NET, then a performance optimization is to use `string.Create`. MA0076 could suggest using `string.Create` directly.
