### ISSUE TITLE
MA0100 doesn't work on using declarations

### ISSUE THREAD

**Issue by js6pak** [meziantou/Meziantou.Analyzer#755]
### Version of the Meziantou.Analyzer NuGet package

2.0.163

### Rule Identifier

MA0100

### Description

MA0100 doesn't work at all with C# 8's `using` declarations.

### Reproduction Steps

Minimal code:

```c#
Task Test()
{
    using var disposable = (IDisposable) null;
    return Task.Delay(1);
}
```
or the example bad code in https://github.com/meziantou/Meziantou.Analyzer/blob/2.0.163/docs/Rules/MA0100.md

### Other information

Adding
```cs
if (parent.ChildOperations.OfType<IUsingDeclarationOperation>().Any())
    return true;
```
to [AwaitTaskBeforeDisposingResourcesAnalyzer.IsInUsingOperation](https://github.com/meziantou/Meziantou.Analyzer/blob/2.0.163/src/Meziantou.Analyzer/Rules/AwaitTaskBeforeDisposingResourcesAnalyzer.cs#L67-L79) seems to work, but I'm not sure whether that's the best approach.

**Comment by meziantou** [comment]
Fixed by https://github.com/meziantou/Meziantou.Analyzer/commit/ee4866d7273882f74eb00116e0b98ae83e620362

**Comment by js6pak** [comment]
@meziantou when would [`if (blockOperation == parent)`](https://github.com/meziantou/Meziantou.Analyzer/blob/ee4866d7273882f74eb00116e0b98ae83e620362/src/Meziantou.Analyzer/Rules/AwaitTaskBeforeDisposingResourcesAnalyzer.cs#L81) ever be the case?

Didn't you mean something like `if (blockOperation == operation)` to protect against cases like this:
```cs
Task Test(bool test)
{
    if (test) goto a;
    return Task.Delay(1);
a:
    ;
    using var disposable = (IDisposable) null;
    return default;
}
```
?

Also when writing the above example I've discovered that labeling the dispose operation breaks the analyzer because it's wrapped with `LabeledOperation`... (which is why I added the empty `;`)

**Comment by meziantou** [comment]
Good catch! I've fixed the logic
