### ISSUE TITLE
Logging template

### ISSUE THREAD

**Issue by LiorBanai** [meziantou/Meziantou.Analyzer#758]
HI,
When using {message} or {Message} in the logging template with serilog it breaks the logging output: aka:
```csharp
Logger.LogInformation(" Message: {message}", text);
```
Is there rule to prevent some strings in logging template (in this case prevent "{message}" or the name message inside the {})?

**Comment by meziantou** [comment]
As indicated in the documentation, you can deny parameters by adding the following line to the configuration file:

````
message;
````

**Comment by LiorBanai** [comment]
found it.
https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0124.md

Thanks!
