### ISSUE TITLE
Avoid MA0042 for MemoryStream

### ISSUE THREAD

**Issue by molinch** [meziantou/Meziantou.Analyzer#774]
### Version of the Meziantou.Analyzer NuGet package

2.0.180

### Rule Identifier

MA0042

### Target Framework

any

### C# Language version

any

### Description

This is a very minor thing, feel free to close it if that's too niche for you :)

If you create and dispose a MemoryStream within the same function, so that the function owns the lifetime of the MemoryStream, then it's quite useless to use any Async flavor. Or favor Async disposal.

Since the MemoryStream, relies on managed memory, it is fully synchronous. Using async over it just adds overhead and in reality, there's even nothing to dispose, but it would feel weird not following the pattern.

### Reproduction Steps

Minimal code:

```c#
using var stream = new MemoryStream();
```

The analyzer wants you to perform async disposal.

**Comment by meziantou** [comment]
Fixed by https://github.com/meziantou/Meziantou.Analyzer/commit/1b0e98c4d000bfbeeead7caa768f9e1c57361577
