### ISSUE TITLE
Provide sample for MA0050 with IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by grosch-intl** [meziantou/Meziantou.Analyzer#776]
Please provide an IAsyncEnumerable example on your MA0050 documentation. For example, I have this method that you're warning about:

```cs
public async IAsyncEnumerable<T> GetCollectionAsync<T>(string collection, [EnumeratorCancellation] CancellationToken cancellationToken)
    where T : class {
    ArgumentException.ThrowIfNullOrWhiteSpace(collection);

    using var cursor = await _database
        .GetCollection<T>(collection)
        .AsQueryable()
        .ToCursorAsync(cancellationToken);

    while (await cursor.MoveNextAsync(cancellationToken))
        foreach (var package in cursor.Current)
            yield return package;
}
```

**Comment by Pretasoc** [comment]
I find, that example translates well fror async enumerators. The suggested code wouls be something like this for your example:

```
public IAsyncEnumerable<T> GetCollectionAsync<T>(string collection, CancellationToken cancellationToken)
    where T : class
{
   ArgumentException.ThrowIfNullOrWhiteSpace(collection);

   return GetCollectionAsync();

   async IAsyncEnumerable<T> GetCollectionAsync<T>()
   {

      using var cursor = await _database
          .GetCollection<T>(collection)
          .AsQueryable()
          .ToCursorAsync(cancellationToken);

      while (await cursor.MoveNextAsync(cancellationToken))
          foreach (var package in cursor.Current)
              yield return package;
  }
}
```

**Comment by grosch-intl** [comment]
Unfortunately, that's a compiler error, because you can't return from an iterator. That's why I was struggling with this one.

**Comment by Pretasoc** [comment]
I'm currently in mobile only, so please excuse, If the following ist wrong, because i didnt Cross checked  It.

You May have overlooked, that i removed the `asnyc` Keywords from the outer method. So ist No iterator method anymore. Its Just a regular method returning an `IAsyncEnumerable<T>` . The iterator was moved to the local function.
________________________________

**Comment by grosch-intl** [comment]
@Pretasoc I did miss that, thank you. Realy appreciate the help.
