### ISSUE TITLE
MA0004 Blazor has a synchronization context

### ISSUE THREAD

**Issue by aljones** [meziantou/Meziantou.Analyzer#96]
Blazor components have a [synchronization context](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#invoke-component-methods-externally-to-update-state).

Blazor components inherit from [Microsoft.AspNetCore.Components.ComponentBase](https://github.com/aspnet/AspNetCore/blob/v3.0.0/src/Components/Components/src/ComponentBase.cs) which implements [Microsoft.AspNetCore.Components.IComponent](https://github.com/aspnet/AspNetCore/blob/v3.0.0/src/Components/Components/src/IComponent.cs).

So I think IComponent should be added to UseConfigureAwaitAnalyzer so it doesn't suggest that ConfigureAwait(false) is needed. If you agree I can make a pull request.  

Thank you for creating these analyzers. They've been very helpful.

**Comment by meziantou** [comment]
Hi,

Thanks for reporting that! I’m on holidays, so I cannot have a look at it right now. You can submit a pull request or wait for a few days :)
