### ISSUE TITLE
Default ruleset modifications

### ISSUE THREAD

**Issue by Mrsevic** [meziantou/Meziantou.Analyzer#98]
Is it a must that extensions must modify active default rule set? I know that in theory it should not be modified but I disabled the extension for performance reasons and last time I took a look there was an reference to this analyzer in the active rule set. 

Thanks

**Comment by meziantou** [comment]
The analyzer is active when the extension is enabled or when you add the NuGet package to your project. It doesn't change any ruleset or editorconfig files by itself. Maybe you can share a repro?

> I disabled the extension for performance reasons

Is the analyzer too slow? Does it use too much resources? Do you have something to share that may help to fix these issues?

**Comment by Mrsevic** [comment]
Thank you for your swift response and the good work you've done. 
> The analyzer is active when the extension is enabled or when you add the NuGet package to your project. It doesn't change any ruleset or editorconfig files by itself. Maybe you can share a repro?

I have used it in .NET Framework 4.5.2 MVC 5 application and Visual Studio 2019 16.3.10 Pro. 
For the moment being here is the screenshot, I'll try to setup an repo(I think the standard mvc 5 template would be sufficient). Might be an M$ bug too, they clearly state that should not be modified. 
![Inkedanalyzer_bug](https://user-images.githubusercontent.com/7526103/69995139-d21df600-154f-11ea-9c60-3e351c80ec9c.jpg)

>  Is the analyzer too slow? Does it use too much resources? Do you have something to share that may help to fix these issues?

To be quite honest, I have not measured. To my naked eye without any analysis whatsoever it is. I do not want to make coding experience not as pleasant as native one(btw it is absolutely not drastic at all). I also have the habit on using the "addins" only when I have a need for them. I have disabled the full solution analysis and the performance is acceptable but I'll stick to disabling/enabling extension upon the need.

The main issue is that even though I disable your extension the ruleset and analysis itself remains enabled, not a big deal but it is weird nevertheless.

**Comment by meziantou** [comment]
There is no code in the extension to change this file. So, it should be the default VS behavior. I suggest you report an issue to the VS team:

![image](https://user-images.githubusercontent.com/509220/69997287-c6b3d600-1521-11ea-8624-2250c70973e7.png)
